    else{dec.add('sphere',[p[0],p[1]-1,p[2]],[3.5,2.6,3.5],'#527eb2');for(let k=0;k<5;k++){let a=k*1.3;dec.line([p[0]+Math.cos(a),p[1]-3,p[2]+Math.sin(a)],[p[0]+Math.cos(a)*1.6,p[1]+k*.45,p[2]+Math.sin(a)*1.6],.2,k%2?'#f2b8bf':'#79ddd5');}}}
   this.meshes.circuitScene=this.mk(dec);const bg=['linear-gradient(#479cde,#a1ece7 76%,#f1e8b6)','linear-gradient(#101c4b,#56529a 80%,#b695b0)','linear-gradient(#063956,#2789a5 70%,#9bdbce)'][this.state.biome],fog=[[.51,.83,.88],[.32,.30,.55],[.14,.48,.60]][this.state.biome];this.e.palette(bg,fog);
  }
  raceKey(){return this.route.id+'-b'+(this.race?.biome??this.state.biome)+'-a'+Number(this.race?.assist??this.state.assist);}
  updateRace(dt){const q=this.race;if(!q||q.finished)return;let axis=(this.keys.has('ArrowRight')||this.keys.has('KeyD')?1:0)-(this.keys.has('ArrowLeft')||this.keys.has('KeyA')?1:0)+(this.steer||0);q.cooldown=Math.max(0,q.cooldown-dt);q.boost=Math.max(0,q.boost-dt);q.bumper=Math.max(0,q.bumper-dt);const braking=this.keys.has('ArrowDown')||this.keys.has('KeyS');const desired=(braking?6:14)+(q.boost>0?11:0);q.speed=mix(q.speed,desired*(q.bumper>0?.5:1),1-Math.exp(-dt*3));q.lateral=clamp(q.lateral+clamp(axis,-1,1)*dt*7,-3.1,3.1);if(q.assist&&!axis)q.lateral*=Math.exp(-dt*.6);const prev=q.d;q.d=Math.min(this.route.length,q.d+q.speed*dt);q.elapsed+=dt;q.vy-=dt*24;q.y=Math.max(0,q.y+q.vy*dt);if(!q.y)q.vy=0;
   for(const ob of q.barriers){if(!ob.hit&&Math.abs(q.d-ob.d)<1.1&&Math.abs(q.lateral-ob.lane)<1.0&&q.y<1.2){ob.hit=true;q.hits++;q.bumper=.55;q.boost=0;this.e.audio.fx('bump');this.note('bump',1.6);}}
   for(const c of q.coins){if(!c.done&&Math.abs(q.d-c.d)<1.25&&Math.abs(q.lateral-c.lane)<1.1){c.done=true;q.collected++;this.e.audio.fx('coin');}}
   while(q.checkpoint<12&&q.d>=this.route.length*(q.checkpoint+1)/12){q.checkpoint++;this.e.audio.fx('good');}
   if(q.elapsed-q.lastRecord>=.20&&q.frames.length<4500){q.frames.push([+q.elapsed.toFixed(3),+q.d.toFixed(3),+q.lateral.toFixed(3),+q.y.toFixed(3)]);q.lastRecord=q.elapsed;}
   this.e.audio.intensity=q.boost>.01?.9:.55;
   if(q.d>=this.route.length){q.finished=true;q.frames.push([+q.elapsed.toFixed(3),+q.d.toFixed(3),+q.lateral.toFixed(3),+q.y.toFixed(3)]);let k=this.raceKey(),best=this.state.bests[k];if(q.timed&&q.elapsed<900&&(!best||q.elapsed<best.time)){this.state.bests[k]={time:+q.elapsed.toFixed(3),frames:q.frames.map(f=>[...f])};let ks=Object.keys(this.state.bests);while(ks.length>8)delete this.state.bests[ks.shift()];this.save();}this.e.audio.fx('finish');this.show('race-result');}
  }
  camera(dt){let eye,target;if(this.type==='race'&&this.race){const q=this.race,a=sample(this.route,q.d),ahead=sample(this.route,Math.min(this.route.length,q.d+12)),p=v.add(a.p,v.mul(a.right,q.lateral));eye=[p[0]-a.dir[0]*10,p[1]+5.1+q.y*.35,p[2]-a.dir[2]*10];target=[ahead.p[0],ahead.p[1]+1.2+q.y*.25,ahead.p[2]];this.r.fov=(innerWidth<600?68:60)+(q.boost>0&&!this.e.settings().reduced?5:0);}
   else{const p=this.p,dist=innerWidth<600?11:10;eye=[p.x+Math.sin(this.camYaw)*Math.cos(this.camPitch)*dist,p.y+1.25+Math.sin(this.camPitch)*dist,p.z+Math.cos(this.camYaw)*Math.cos(this.camPitch)*dist];target=[p.x,p.y+1.4,p.z];this.r.fov=innerWidth<600?66:57;for(const c of this.colliders){const a=[eye[0]-p.x,eye[2]-p.z],u=clamp(((c.x-p.x)*a[0]+(c.z-p.z)*a[1])/(a[0]**2+a[1]**2||1),0,1);if(u>.08&&Math.hypot(p.x+a[0]*u-c.x,p.z+a[1]*u-c.z)<c.r+.2){const f=Math.max(.30,u-.24);eye=v.add(target,v.mul(v.sub(eye,target),f));}}}
   const k=1-Math.exp(-dt*7);this.eye=this.eye.map((x,i)=>mix(x,eye[i],k));this.target=this.target.map((x,i)=>mix(x,target[i],k));return{eye:this.eye,target:this.target};}
  scene(){if(!this.loaded)return[];let list=[];const add=(...x)=>this.add(...x);if(this.type==='race'&&this.race){const q=this.race,r=this.route;list.push(add(this.meshes.road),add(this.meshes.circuitScene,[0,0,0],[1,1,1],[0,0,0],{cast:false}));
    const place=(mesh,d,lateral,y=0,s=[1,1,1],alpha=1)=>{const a=sample(r,d),p=v.add(a.p,v.mul(a.right,lateral));list.push(add(mesh,[p[0],p[1]+y,p[2]],s,[0,a.yaw,0],{alpha,cast:alpha===1}));};
    for(const o of q.barriers)if(Math.abs(o.d-q.d)<95)place(this.meshes.barrier,o.d,o.lane,0,[1,1,1],o.hit?.35:1);
    for(const c of q.coins)if(!c.done&&Math.abs(c.d-q.d)<90)place(this.e.meshes.coin,c.d,c.lane,1.0,[1,1,1]);
    for(let i=0;i<12;i++){const d=(i+1)/12*r.length;if(Math.abs(d-q.d)<100)place(this.meshes.hoop,d,0,0,[1,1,1],i<q.checkpoint?.23:1);}
    const a=sample(r,q.d),p=v.add(a.p,v.mul(a.right,q.lateral));list.push(add(this.meshes.vehicle,[p[0],p[1]+q.y+.25,p[2]],[1,1,1],[0,a.yaw,(this.steer||0)*-.06]));
    // A small Rayyan riding the original hovercraft: actual articulated 3D, not a billboard.
    const rider=RayyanModel.items(this.e.avatar(),this.e.meshes.shadow,this.e.meshes.wing,[0,0,0],0,this.time,{...this.p,speed:0,ground:true,glide:false},false,'idle',this.e.settings().reduced);const base=M.compose([p[0],p[1]+q.y+.56,p[2]+0],[.48,.48,.48],[0,a.yaw,0]);for(const it of rider)if(it.mesh!==this.e.meshes.shadow)list.push({...it,matrix:M.mul(base,it.matrix)});
    const best=this.state.bests[this.raceKey()];if(best&&q.timed&&!q.finished&&best.frames.length){const fs=best.frames;let i=Math.min(fs.length-1,Math.floor(q.elapsed/.20));while(i>0&&fs[i][0]>q.elapsed)i--;while(i<fs.length-2&&fs[i+1][0]<q.elapsed)i++;const f=fs[i],g=fs[Math.min(i+1,fs.length-1)],u=clamp((q.elapsed-f[0])/Math.max(.001,g[0]-f[0]),0,1);place(this.meshes.vehicle,mix(f[1],g[1],u),mix(f[2],g[2],u),mix(f[3],g[3],u)+.25,[1,1,1],.28);}
   }else{list=[...this.world,add(this.meshes.bridge),add(this.meshes.pipes)];const p=this.p;list.push(...RayyanModel.items(this.e.avatar(),this.e.meshes.shadow,this.e.meshes.wing,[p.x,p.y,p.z],p.yaw,this.time,p,false,'idle',this.e.settings().reduced));const npc=RayyanModel.items(this.guideAvatar,this.e.meshes.shadow,this.e.meshes.wing,[4,0,-4],Math.PI,this.time,{...p,ground:true,glide:false,slide:0,speed:0},true,'idle',this.e.settings().reduced);list.push(...npc);const noor=this.state.noor?[26,1.45,4]:[p.x+1.25,p.y+2.4,p.z+.4];list.push(add(this.e.meshes.noor,[noor[0],noor[1]+Math.sin(this.time*2)*.1,noor[2]],[.9,.9,.9],[0,p.yaw,0]));list.push(add(this.meshes.vehicle,[-9,.35,9],[1,1,1],[0,Math.PI/4,0]));
    if(this.state.stage===0)list.push(add(this.meshes.key,[-12,1.6+Math.sin(this.time*2)*.08,-5],[1,1,1],[0,this.time*.65,0]));
    for(let i=0;i<this.discoveries.length;i++){const q=this.discoveries[i];if(!this.state.discoveries.includes(i))list.push(add(this.e.meshes.coin,[q[0],1.2,q[2]],[1,1,1],[0,this.time,0],{cast:false}));}
    if(this.builder&&this.state.stage===2){const total=this.state.bridge.reduce((a,b)=>a+b,0),len=this.selectedBeam;list.push(add(this.e.meshes.pad,[16+total+len/2,.07,0],[len/6.9,1,1.3],[0,0,0],{alpha:total+len<=8?.4:.13,cast:false}));}
    const dest=this.destination();if(this.state.stage<4)list.push(add(this.meshes.beacon,dest.p,[1,1,1],[0,0,0],{cast:false}));
    if(this.bloom){for(const [x,z]of[[31,-8],[38,-8],[40,5],[31,7]])list.push(add(this.meshes.palm,[x,0,z],[1.3,this.bloom*1.3,1.3]));list.push(add(this.e.meshes.help,[36,.25,0],[2.3,.14,2.3],[0,0,0],{cast:false}));for(let i=0;i<20;i++){let a=i*TAU/20,f=(this.time*.6+i*.137)%1;list.push(add(this.meshes.spark,[36+Math.cos(a)*f*1.7,.5+Math.sin(f*Math.PI)*2.1,Math.sin(a)*f*1.7],[.3,.36,.3],[0,0,0],{cast:false,alpha:this.bloom*.8}));}}
    if(this.state.noor){const wet=this.wet();for(const i of wet){const [x,z]=this.pipeNodes[i];list.push(add(this.meshes.spark,[x,.68+Math.sin(this.time*3+i)*.03,z],[.33,.14,.33],[0,0,0],{cast:false}));}}
    for(let i=0;i<10;i++){let a=i*TAU/10;list.push(add(this.meshes.cloud,[Math.cos(a)*38,-5,Math.sin(a)*32],[1.5,1,1.5],[0,a,0],{cast:false}));}
   }
   const opaque=list.filter(x=>(x.alpha??1)>=.99),transparent=list.filter(x=>(x.alpha??1)<.99);transparent.sort((a,b)=>Math.hypot(b.matrix[12]-this.eye[0],b.matrix[13]-this.eye[1],b.matrix[14]-this.eye[2])-Math.hypot(a.matrix[12]-this.eye[0],a.matrix[13]-this.eye[1],a.matrix[14]-this.eye[2]));return[...opaque,...transparent];
  }
  sync(){if(!this.active)return;const T=k=>this.t(k),q=this.race,race=this.type==='race',p=this.p;this.ui.dataset.panelOpen=String(!!this.panel||this.e.paused());this.$('gxTitle').textContent=race?T('race'):T('name');this.$('gxSubtitle').textContent=race?T(['beach','moon','sea'][q?.biome??this.state.biome]):T('edition');this.$('gxLang').textContent=this.e.settings().lang==='ar'?'EN':'عربي';for(const [id,k]of[['gxBook','journal'],['gxHelp','guide'],['gxPause','pause'],['gxJoy','startControls']])this.$(id).setAttribute('aria-label',T(k));
   this.$('gxValue').textContent=race?(q.timed?q.elapsed.toFixed(1)+' s':'∞'):T('val'+this.state.stage);this.$('gxObjective').textContent=race?`${T('lap')} · ${q.checkpoint} / 12`:T('quest'+this.state.stage);const c=this.context();this.$('gxInteract').hidden=!!this.panel||this.e.paused()||!c;this.$('gxInteract').textContent=c?T(c.label):'';this.$('gxBuilder').hidden=!(this.builder&&c?.id==='bridge'&&!this.panel);this.$('gxLength').textContent=`${this.state.bridge.reduce((a,b)=>a+b,0)} / 8 m`;this.$('gxUndo').disabled=!this.state.bridge.length;this.$('gxUndo').setAttribute('aria-label',T('undo'));this.ui.querySelectorAll('[data-beam-gx]').forEach(b=>{const on=+b.dataset.beamGx===this.selectedBeam;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on));});this.$('gxJoy').hidden=race;this.$('gxSteer').hidden=!race;this.$('gxJump').querySelector('small').textContent=T('jump');this.$('gxAlt').querySelector('small').textContent=T(race?'boost':'glide');this.$('gxAlt').setAttribute('aria-label',T(race?'boost':'glide'));this.$('gxJump').setAttribute('aria-label',T('jump'));this.$('gxSpeed').hidden=!race;this.$('gxKeys').textContent=race?T('raceKeys'):this.tr('WASD حركة · Space قفز/جناح · E تفاعل · H مساعدة · M الدفتر','WASD MOVE · SPACE JUMP/GLIDE · E INTERACT · H HELP · M JOURNAL');
   const compass=this.$('gxCompass');if(race){compass.firstElementChild.textContent='◷';let best=this.state.bests[this.raceKey()];compass.lastElementChild.textContent=best?`${T('best')}: ${best.time.toFixed(2)} s`:T('none');this.$('gxSpeed').querySelector('strong').textContent=Math.round(q.speed*3.6);this.$('gxSpeed').querySelector('small').textContent=this.tr('وحدة سرعة لعب','GAME SPEED');this.$('gxSpeed').querySelector('i').style.width=(1-q.cooldown/5.3)*100+'%';this.$('gxTarget').hidden=true;}
   else{const d=this.destination(),dist=Math.hypot(p.x-d.p[0],p.z-d.p[2]),angle=Math.atan2(d.p[0]-p.x,-(d.p[2]-p.z))+this.camYaw;compass.firstElementChild.textContent='↑';compass.firstElementChild.style.transform=`rotate(${angle}rad)`;compass.lastElementChild.textContent=Math.round(dist)+' m';const z=this.r.project([d.p[0],2.9,d.p[2]]);const target=this.$('gxTarget');target.hidden=!!this.panel||this.e.paused()||!z?.visible||dist<2.5||z.y<145||z.y>innerHeight-175;if(!target.hidden){target.textContent=d.name;target.style.left=clamp(z.x,90,innerWidth-90)+'px';target.style.top=z.y+'px';}}
   if(this.tick%8===0)this.drawMini();
  }
  drawMini(){const c=this.$('gxMap'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);if(this.type==='race'){this.drawRouteMap(c,this.route);return;}const xy=(x,z)=>[48+x*3.8,126+z*4];for(const [x,z,r]of[[0,0,17],[35,0,11]]){const a=xy(x,z);ctx.beginPath();ctx.arc(...a,r*3.6,0,TAU);ctx.fillStyle='#81b7ab';ctx.fill();}ctx.strokeStyle='#ffe699';ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(...xy(16,0));ctx.lineTo(...xy(16+this.state.bridge.reduce((a,b)=>a+b,0),0));ctx.stroke();for(const [point,col,rad]of[[this.destination().p,'#ffe389',6],[[this.p.x,0,this.p.z],'#ffffff',5]]){ctx.beginPath();ctx.arc(...xy(point[0],point[2]),rad,0,TAU);ctx.fillStyle=col;ctx.fill();}}
  drawRouteMap(c,r){if(!c||!r)return;const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);const xs=r.pts.map(p=>p[0]),zs=r.pts.map(p=>p[2]),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs),scale=Math.min((c.width-30)/(maxX-minX||1),(c.height-24)/(maxZ-minZ||1));ctx.strokeStyle='#87f8db';ctx.lineWidth=3;ctx.beginPath();r.pts.forEach((p,i)=>{let x=(p[0]-(minX+maxX)/2)*scale+c.width/2,y=(p[2]-(minZ+maxZ)/2)*scale+c.height/2;if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y);});ctx.stroke();}
  async importRoute(file){try{if(!file||file.size>4e6)throw Error('SIZE');const raw=JSON.parse(await file.text());this.localRoute=routeInfo(normaliseRoute(raw));if(this.panel==='lab')this.drawPanel();return true;}catch(e){if(this.$('gxRouteReport'))this.$('gxRouteReport').textContent=this.t('badRoute');return false;}}
  download(name,data){const u=URL.createObjectURL(new Blob([data],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2000);}
  exportSave(){this.save();this.download('nabigha-expedition-progress.json',JSON.stringify(this.state,null,2));this.note('saved');}
  async importSave(file){try{if(!file||file.size>1.5e6)throw Error('SIZE');const s=validate(JSON.parse(await file.text()));this.state=s;this.bloom=s.stage===4?1:0;this.save();if(this.loaded){this.rebuildBridge();this.rebuildWater();}await this.e.start('world');this.note('restored');return true;}catch(e){this.note('invalid');if(this.panel){const p=document.createElement('p');p.textContent=this.t('invalid');this.box.appendChild(p);}return false;}}
  snapshot(){return{active:this.active,type:this.type,panel:this.panel,state:JSON.parse(JSON.stringify(this.state)),p:{...this.p},context:this.context(),destination:this.destination(),bridgeLength:this.state.bridge.reduce((a,b)=>a+b,0),wet:[...this.wet()],waterSolved:this.solved(),bloom:this.bloom,builder:this.builder,selectedBeam:this.selectedBeam,storageOK:this.ok,localRoute:this.localRoute?{id:this.localRoute.id,points:this.localRoute.pts.length,length:this.localRoute.length}:null,route:{id:this.route.id,points:this.route.pts.length,length:this.route.length},race:this.race?{d:this.race.d,elapsed:this.race.elapsed,speed:this.race.speed,lateral:this.race.lateral,y:this.race.y,checkpoint:this.race.checkpoint,finished:this.race.finished,timed:this.race.timed,local:this.race.local,collected:this.race.collected,hits:this.race.hits,frames:this.race.frames.length,key:this.raceKey(),ghost:!!this.state.bests[this.raceKey()]}:null};}
 }
 return{Expedition,validate,normaliseRoute,routeInfo,sample,glbInfo,version:'3.0.0-preview.1',words:WORDS};
})();
