   b.add('box',[4,1.5,-8],[5.2,3,3.3],'#ebdfb6');b.add('box',[4,3.05,-8],[5.45,.25,3.5],'#397d85');this.arch(b,4,.05,-6.26,2.1,2.6,'#f7ecc7');b.add('box',[4,1.15,-6.3],[1.8,2.3,.05],'#16485e');for(let x of[2,6]){b.add('box',[x,3.6,-8],[.8,1.2,.8],'#e2d6aa');b.add('box',[x,4.3,-8],[1,.25,1],'#438d8e');}
   this.colliders.push({x:4,z:-8,r:2.8});
   // Futuristic solar canopy, geometric arcades and animated relay garden.
   for(let x of[-6,0,6]){b.add('cylinder',[x,1.5,-13],[.13,3,.13],'#eee5bc');b.add('box',[x,3.0,-13],[3.2,.12,2.2],'#316686',[.23,0,0]);for(let k=-1;k<=1;k++)b.add('box',[x+k*.8,3.08,-12.95],[.04,.04,2.1],'#7ee0d2',[.23,0,0],.25);}
   for(let x of[-12,-6,0,6,12]){for(let z of[-1,2,5,8])b.add('cylinder',[x*.5,.045,z],[.55,.06,.4],'#edf4d6');}
   for(let z of[-2.6,2.6]){b.add('box',[14.5,.16,z],[2,.25,.5],'#e7edcb');}
   b.add('cylinder',[14,.08,0],[1.65,.16,1.65],'#517b92');b.add('ring',[14,.22,0],[1.3,1.8,1.3],'#ffe17a',[0,0,0],.35);
   b.add('cylinder',[-9,.08,9],[2.4,.16,2.4],'#437c98');b.add('ring',[-9,.21,9],[2,1,2],'#93f9de',[0,0,0],.3);
   for(let z of[-11,-7,7,11])for(let x of[-14,14])this.world.push(this.add(this.meshes.palm,[x,0,z],[1.1,1.1,1.1]));
   // Observable water source and dry pond.
   b.add('cylinder',[25,.65,0],[.8,1.3,.8],'#edf1d3');b.add('sphere',[25,1.5,0],[.7,.6,.7],'#7ce5d8');b.add('cylinder',[36,.13,0],[2.5,.25,2.5],'#dbcb9c');b.add('ring',[36,.33,0],[2.2,2.0,2.2],'#eadeba');b.add('cylinder',[26,.08,4],[1.2,.16,1.2],'#8acbbb');b.add('ring',[26,.2,4],[1,1,1],'#f0fff1');
   for(const [x,z]of[[31,-8],[38,-8],[40,5],[31,7]]){b.add('cylinder',[x,.1,z],[.9,.20,.9],'#ebd4a3');b.add('cylinder',[x,.7,z],[.12,1.4,.12],'#b39a77');}
   for(let z=-8;z<=8;z+=4)this.arch(b,43,.1,z,3.0,4,'#e6e0c0');
   this.world.unshift(this.add(this.mk(b)));
   b=new Builder();for(let i=0;i<18;i++){const a=i/18*TAU,x=Math.cos(a)*72,z=Math.sin(a)*64,h=8+(i%5)*3;b.add('box',[x,h/2-6,z],[3+i%3,h,4],'#407caa');for(let y=0;y<h-4;y+=2)b.add('box',[x,y,z+2.02],[2,.5,.06],'#8fe6dd',[0,0,0],.2);}this.world.unshift(this.add(this.mk(b),[0,0,0],[1,1,1],[0,0,0],{cast:false}));
   this.rebuildBridge();this.rebuildWater();
  }
  rebuildBridge(){if(this.meshes.bridge)this.r.dispose(this.meshes.bridge);let b=new Builder(),x=16;for(const len of this.state.bridge){b.add('box',[x+len/2,.12,0],[len-.055,.22,3],'#e6d5a1');for(let z of[-1.42,1.42]){b.line([x+.1,.2,z],[x+.1,1.2,z],.065,'#37b8b1');b.line([x+.1,1.16,z],[x+len-.1,1.16,z],.045,'#90ddd0');}for(let q=.25;q<len;q+=.5)b.add('box',[x+q,.247,0],[.035,.025,2.95],'#ae9672');x+=len;}this.meshes.bridge=this.mk(b);}
  wet(){if(!this.state.noor)return new Set();const wet=new Set([0]),queue=[0];while(queue.length){let i=queue.shift(),p=this.pipeNodes[i],edges=i===0?[3,1]:[this.state.rot[i-1],(this.state.rot[i-1]+1)%4];for(const d of edges){const offset=[[0,-3],[3,0],[0,3],[-3,0]][d];const j=this.pipeNodes.findIndex(a=>a[0]===p[0]+offset[0]&&a[1]===p[1]+offset[1]);if(j>0&&!wet.has(j)){const r=this.state.rot[j-1];if([r,(r+1)%4].includes((d+2)%4)){wet.add(j);queue.push(j);}}}}return wet;}
  solved(){return this.wet().has(4)&&[this.state.rot[3],(this.state.rot[3]+1)%4].includes(1);}
  rebuildWater(){if(this.meshes.pipes)this.r.dispose(this.meshes.pipes);const b=new Builder(),wet=this.wet();this.pipeNodes.forEach(([x,z],i)=>{const edges=i===0?[3,1]:[this.state.rot[i-1],(this.state.rot[i-1]+1)%4],on=wet.has(i);b.add('cylinder',[x,.16,z],[.85,.32,.85],'#ecdeb8');for(const edge of edges){const [dx,dz]=[[0,-1.5],[1.5,0],[0,1.5],[-1.5,0]][edge];b.line([x,.45,z],[x+dx,.45,z+dz],.18,'#508996');b.line([x,.62,z],[x+dx,.62,z+dz],.065,on?'#92ffe3':'#b3c9c7',on?.7:0);}if(i){b.line([x,.43,z],[x,.95,z],.045,'#c5a15b');b.add('ring',[x,1,z],[.34,1.6,.34],'#f4cf69');b.line([x-.3,1,z],[x+.3,1,z],.028,'#d4ac4c');}});b.line([33.5,.46,0],[34.0,.46,0],.18,'#578c97');this.meshes.pipes=this.mk(b);}
  async start(type='world',opts={}){this.initMeshes();this.active=true;this.type=type;this.ui.hidden=false;document.body.dataset.globalMode=type;this.noteEnd=0;this.$('gxNote').textContent='';this.builder=false;this.clearInput();this.panel='';this.overlay.hidden=true;this.ui.dataset.panelOpen='false';
   if(type==='world'){this.route=this.route||originalRoute();this.checkpoint=this.state.stage>=3?[25,0,5]:this.state.stage>=2?[9,0,3]:[0,0,10];const [x,y,z]=this.checkpoint;Object.assign(this.p,{x,y,z,vy:0,yaw:0,ground:true,speed:0,glide:false,step:0});this.camYaw=0;this.eye=[x,6,z+10];this.target=[x,1.4,z];this.e.palette('linear-gradient(#368bc2,#9be4e4 70%,#deefe6)',[.5,.83,.86]);}
   else{this.route=opts.local&&this.localRoute?this.localRoute:originalRoute();this.buildCircuit();const local=!!(opts.local&&this.localRoute),timed=opts.timed!==false;this.race={d:0,lateral:0,vy:0,y:0,speed:0,elapsed:0,checkpoint:0,collected:0,hits:0,boost:0,cooldown:0,bumper:0,timed,local,assist:this.state.assist,biome:this.state.biome,finished:false,frames:[],lastRecord:-1,coins:Array.from({length:22},(_,i)=>({d:this.route.length*(i+1)/24,lane:Math.sin(i*.85)>0?2.2:-2.2,done:false})),barriers:Array.from({length:9},(_,i)=>({d:this.route.length*(i+1)/11,lane:(i%3-1)*2.2,hit:false}))};const s=sample(this.route,0);this.eye=[s.p[0]-s.dir[0]*10,s.p[1]+5,s.p[2]-s.dir[2]*10];this.target=[s.p[0]+s.dir[0]*10,s.p[1]+1.5,s.p[2]+s.dir[2]*10];}
   this.lastUI='';this.sync();await this.e.audio.unlock();if(!this.active)return;this.e.audio.start();this.e.canvas.focus();if(type==='world'&&this.state.stage===0)this.show('intro');if(!this.ok)this.note('saveFail',6);}
  exit(){this.save();this.active=false;this.type='world';this.panel='';this.ui.hidden=true;this.overlay.hidden=true;this.clearInput();delete document.body.dataset.globalMode;this.e.leave();}
  destination(){if(this.type==='race'){const d=(this.race.checkpoint+1)/12*this.route.length;return{p:sample(this.route,Math.min(this.route.length,d)).p,name:this.t('lap')};}let s=this.state.stage;if(s===0)return{p:[-12,0,-5],name:this.t('key')};if(s===1)return{p:[4,0,-4],name:this.t('keeper')};if(s===2)return{p:[14,0,0],name:this.t('bridge')};if(s===3&&!this.state.noor)return{p:[26,0,4],name:this.t('pump')};if(s===3){let i=this.state.rot.findIndex((a,i)=>a!==[3,1,2,0][i]);i=Math.max(0,i);return{p:[this.pipeNodes[i+1][0],0,this.pipeNodes[i+1][1]],name:this.t('pipe')+' '+(i+1)};}return{p:[36,0,0],name:this.t('pond')};}
  context(){if(this.type!=='world'||this.panel||this.p.y>.8)return null;let p=this.p,d=(x,z)=>Math.hypot(p.x-x,p.z-z),s=this.state.stage;if(s===0&&d(-12,-5)<2.4)return{id:'key',label:'pick'};if(d(4,-4)<2.5)return{id:'keeper',label:s===1?'returnKey':'guide'};if(d(14,0)<2.5&&s<3)return{id:'bridge',label:this.builder?'place':'openBuild'};if(d(26,4)<2.2&&s>=3&&!this.state.noor)return{id:'noor',label:'hold'};if(s>=3&&s<4)for(let i=1;i<5;i++)if(d(...this.pipeNodes[i])<1.65)return{id:'pipe',i:i-1,label:'rotate'};if(s===4&&d(36,0)<2.7)return{id:'pond',label:'inspect'};if(d(-9,9)<2.6)return{id:'dock',label:'race'};return null;}
  interact(){if(!this.canPlay())return;const c=this.context();if(!c)return;const s=this.state;if(c.id==='key'){s.stage=1;this.note('keyFound');this.e.audio.fx('coin');}
   if(c.id==='keeper'){if(s.stage===1){s.stage=2;this.checkpoint=[9,0,3];this.note('keyReturned');this.e.audio.fx('good');}else{this.show('guide');return;}}
   if(c.id==='bridge'){if(s.stage<2){this.note('needKey');return;}if(!this.builder){this.builder=true;this.sync();return;}this.place();return;}
   if(c.id==='noor'){s.noor=true;this.rebuildWater();this.note('held');this.e.audio.fx('help');this.maybeWater();}
   if(c.id==='pipe'){s.rot[c.i]=(s.rot[c.i]+1)%4;this.rebuildWater();this.e.audio.fx('click');this.maybeWater();}
   if(c.id==='pond'){this.show('journal');return;}if(c.id==='dock'){this.show('race-select');return;}this.save();this.lastUI='';this.sync();}
  place(){if(!this.canPlay()||this.state.stage!==2||this.context()?.id!=='bridge')return false;const total=this.state.bridge.reduce((a,b)=>a+b,0);if(total+this.selectedBeam>8){this.note('beamFull');this.e.audio.fx('wrong');return false;}this.state.bridge.push(this.selectedBeam);this.rebuildBridge();this.e.audio.fx('good');if(total+this.selectedBeam===8){this.state.stage=3;this.builder=false;this.checkpoint=[25,0,5];this.note('built');}this.save();this.lastUI='';this.sync();return true;}
  undo(){if(!this.canPlay()||this.state.stage!==2||this.context()?.id!=='bridge'||!this.state.bridge.length)return;this.state.bridge.pop();this.rebuildBridge();this.save();this.sync();}
  maybeWater(){if(this.state.stage===3&&this.solved()){this.state.stage=4;this.note('water',6);this.e.audio.fx('finish');this.save();}}
  floor(x,z){if(Math.hypot(x,z)<17.7||Math.hypot(x-35,z)<11.8)return 0;let len=this.state.bridge.reduce((a,b)=>a+b,0);if(x>=15.8&&x<=16+len+.05&&Math.abs(z)<1.45)return .24;return -99;}
  jump(){if(!this.canPlay())return;if(this.type==='race'){if(this.race.y<.02){this.race.vy=8.6;this.e.audio.fx('jump');}return;}if(this.p.ground){this.p.vy=9.2;this.p.ground=false;this.p.glide=false;this.e.audio.fx('jump');}else{this.p.glide=!this.p.glide;if(this.p.glide)this.e.audio.fx('wing');}}
  boost(){if(!this.canPlay()||this.type!=='race'||this.race.cooldown>0)return;this.race.boost=1.15;this.race.cooldown=5.3;this.e.audio.fx('boost');}
  update(dt){if(!this.canPlay())return;this.time+=dt;this.tick++;if(this.noteEnd&&this.time>this.noteEnd){this.$('gxNote').textContent='';this.noteEnd=0;}if(this.type==='race'){this.updateRace(dt);return;}const p=this.p,old=p.y;
   if(this.keys.has('KeyQ'))this.camYaw+=dt*1.7;if(this.keys.has('KeyC'))this.camYaw-=dt*1.7;
   let f=(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0)-(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0)-this.joy.y,s=(this.keys.has('KeyD')||this.keys.has('ArrowRight')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')?1:0)+this.joy.x,n=Math.hypot(f,s);if(n>1){f/=n;s/=n;n=1;}if(n<.07)f=s=n=0;let speed=p.glide?8.2:this.keys.has('ShiftLeft')?8:5.5;
   const dx=(s*Math.cos(this.camYaw)-f*Math.sin(this.camYaw))*speed*dt,dz=(-s*Math.sin(this.camYaw)-f*Math.cos(this.camYaw))*speed*dt;p.x+=dx;p.z+=dz;p.speed=n*speed;p.step+=p.speed*dt*1.5;if(n){let a=Math.atan2(-dx,-dz);p.yaw+=Math.atan2(Math.sin(a-p.yaw),Math.cos(a-p.yaw))*Math.min(1,dt*12);}
   for(const c of this.colliders){let dx=p.x-c.x,dz=p.z-c.z,d=Math.hypot(dx,dz),r=c.r+.4;if(d<r&&p.y<3.2){p.x=c.x+dx/Math.max(d,.001)*r;p.z=c.z+dz/Math.max(d,.001)*r;}}
   p.vy-=dt*(p.glide?4.8:24);if(p.glide)p.vy=Math.max(-1.25,p.vy);p.y+=p.vy*dt;const floor=this.floor(p.x,p.z);if(p.y<=floor&&old>=floor-.3&&p.vy<=0){p.y=floor;p.vy=0;p.ground=true;p.glide=false;}else p.ground=false;
   if(p.y< -6){[p.x,p.y,p.z]=this.checkpoint;p.vy=0;p.ground=true;p.glide=false;this.note('safe');}
   for(let i=0;i<this.discoveries.length;i++){const q=this.discoveries[i];if(!this.state.discoveries.includes(i)&&Math.hypot(p.x-q[0],p.z-q[2])<1.1&&p.y<1.7){this.state.discoveries.push(i);this.save();this.e.audio.fx('coin');this.note('found',2.3);}}
   if(this.state.stage===4)this.bloom=Math.min(1,this.bloom+dt/2.5);if(this.builder&&this.context()?.id!=='bridge')this.builder=false;this.e.audio.intensity=p.glide?.65:.15;
  }
  buildCircuit(){if(this.meshes.road)this.r.dispose(this.meshes.road);if(this.meshes.circuitScene)this.r.dispose(this.meshes.circuitScene);const r=this.route,b=new Builder(),col=['#72becf','#596baa','#469aa4'][this.state.biome],trim=['#6dfad8','#c4a8fa','#9effcc'][this.state.biome];
   for(let i=0;i<r.pts.length-1;i++){const a=sample(r,r.lens[i]),q=sample(r,r.lens[i+1]),at=(s,x,y=0)=>v.add(s.p,v.add(v.mul(s.right,x),[0,y,0]));b.quad(at(a,-4),at(q,-4),at(q,4),at(a,4),col);b.quad(at(a,-4,-.25),at(a,-4),at(q,-4),at(q,-4,-.25),'#2f5676');b.quad(at(a,4),at(a,4,-.25),at(q,4,-.25),at(q,4),'#2f5676');for(const x of[-3.92,3.92])b.quad(at(a,x-.075,.035),at(q,x-.075,.035),at(q,x+.075,.035),at(a,x+.075,.035),trim,.2);if(i%3===0)b.quad(at(a,-.05,.02),at(q,-.05,.02),at(q,.05,.02),at(a,.05,.02),'#e6ffe8');}
   this.meshes.road=this.mk(b);const dec=new Builder();const floorY=Math.min(...r.pts.map(p=>p[1]))-7;dec.add('cylinder',[0,floorY,0],[110,.15,110],this.state.biome===0?'#3eabb5':this.state.biome===1?'#353e71':'#215f88');
   for(let i=0;i<32;i++){const s=sample(r,r.length*(i+.3)/32),side=i%2?1:-1,p=v.add(s.p,v.mul(s.right,side*(9+i%3*4)));if(this.state.biome===0){dec.add('cylinder',[p[0],p[1]-2,p[2]],[3.7,.5,3.7],'#e7d7a2');dec.add('cylinder',[p[0],p[1]-.6,p[2]],[.2,3,.2],'#bc925e');for(let k=0;k<5;k++){let a=k*TAU/5;dec.line([p[0],p[1]+1,p[2]],[p[0]+Math.cos(a)*2.2,p[1]+1.3,p[2]+Math.sin(a)*2.2],.24,'#79c890');}}
    else if(this.state.biome===1){dec.add('rock',[p[0],p[1]-2,p[2]],[3+i%3,2,3],'#686ba3');dec.add('ring',[p[0],p[1]+2,p[2]],[2,1,2],'#97e3ee',[Math.PI/2,i,0],.25);}
