/* Nabigha GLOBAL 3.0 preview. Original geometry, quests and arcade physics.
   Imported routes stay local; no third-party models, audio or fonts are distributed.
   Real multiplayer, glTF/Draco rendering, and commercial release are NOT implemented. */
'use strict';
window.NabighaGlobal = (()=>{
 const {Builder,M,v,TAU}=N3;
 const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)), mix=(a,b,t)=>a+(b-a)*t;
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const STORE='nabigha.global.expedition.v1';
 const WORDS={
 name:['بعثة الإعمار','THE RESTORATION EXPEDITION'],edition:['نابغة · معاينة 3.0','NABIGHA · 3.0 PREVIEW'],launch:['ابدأ بعثة الإعمار','START THE EXPEDITION'],race:['مضمار الآفاق','HORIZON CIRCUIT'],lab:['مختبر المرفقات','LOCAL ASSET LAB'],resume:['تابع المغامرة','RESUME'],home:['الواجهة الرئيسية','MAIN MENU'],pause:['وقفة هادئة','TAKE A BREAK'],guide:['دليل الرحلة','FIELD GUIDE'],journal:['دفتر المستكشف','EXPLORER JOURNAL'],settings:['الإعدادات والصوت','SETTINGS & AUDIO'],close:['إغلاق','CLOSE'],leave:['العودة إلى المدينة','RETURN TO THE CITY'],jump:['قفز','JUMP'],glide:['جناح','GLIDE'],boost:['اندفاع','BOOST'],brake:['إبطاء','BRAKE'],action:['تفاعل','INTERACT'],undo:['تراجع','UNDO'],place:['ركّب القطعة','PLACE BEAM'],end:['اكتملت الجولة','CIRCUIT COMPLETE'],again:['جولة جديدة','ANOTHER LAP'],export:['حفظ نسخة تقدم','EXPORT PROGRESS'],import:['استعادة التقدم','IMPORT PROGRESS'],ready:['جاهز','READY'],assist:['مساعدة القيادة','STEERING ASSIST'],free:['استكشاف بلا توقيت','UNTIMED EXPLORATION'],raceMode:['تحدّي نفسك','PERSONAL TIME TRIAL'],
 beach:['ساحل الفجر','DAWN COAST'],moon:['مدار الحكمة','WISDOM ORBIT'],sea:['حدائق المرجان','CORAL GARDENS'],
 startTitle:['مدينة تنتظر أثرك','A CITY WAITING FOR YOUR CONTRIBUTION'],startText:['ضاع مفتاح سالم الشمسي، والجسر متوقف، والواحة عطشى. ابحث عن المفتاح وأعده، ابنِ جسرًا بطريقتك، ثم تعاون مع نور لإيصال الماء. لا مؤقّت للمهمات، ولا عقوبة على المحاولة.','Salim has lost his solar key. A bridge is unfinished, and the oasis needs water. Return the key, build a bridge your way, then work with Noor to connect the water. No quest timer and no penalty for trying.'],startControls:['الأسهم أو WASD للحركة · Space للقفز ثم الجناح · E للتفاعل. على الهاتف: العصا اليسرى والأزرار اليمنى. اسحب المشهد لتدوير الكاميرا.','Arrows or WASD to move · Space to jump, then glide · E to interact. On phones: left stick and right buttons. Drag the scene to turn the camera.'],
 quest0:['اعثر على المفتاح قرب النخلة','Find the key near the palm'],quest1:['أعد المفتاح إلى سالم','Return the key to Salim'],quest2:['ابنِ جسرًا بطول ٨ أمتار','Build an 8-metre bridge'],quest3:['تعاون مع نور لتوصيل الماء','Work with Noor to connect the water'],quest4:['الواحة تزهر. استكشف بحرية','The oasis blooms. Explore freely'],
 val0:['الأمانة','TRUST'],val1:['الأمانة','TRUST'],val2:['الإتقان','CRAFT'],val3:['التعاون وحفظ النعمة','TEAMWORK & CARE'],val4:['أثر باقٍ','LASTING CHANGE'],
 key:['المفتاح الشمسي','SOLAR KEY'],keeper:['سالم · صاحب المفتاح','SALIM · KEY OWNER'],bridge:['ورشة الجسر','BRIDGE WORKSHOP'],pump:['منصة نور','NOOR’S RELAY'],pipe:['صمام الماء','WATER VALVE'],pond:['الواحة','OASIS'],dock:['رصيف المركبة','HOVERCRAFT DOCK'],
 pick:['التقط المفتاح','PICK UP KEY'],returnKey:['أعد المفتاح إلى سالم','RETURN KEY TO SALIM'],openBuild:['افتح أدوات البناء','OPEN BUILD TOOLS'],hold:['اطلب من نور تثبيت المضخة','ASK NOOR TO HOLD THE PUMP'],rotate:['دوّر الصمام ربع دورة','ROTATE VALVE 90°'],inspect:['شاهد ما تغيّر','SEE WHAT CHANGED'],
 keyFound:['وجدت المفتاح! صاحبه ينتظرك عند الورشة.','Key found! Its owner is waiting by the workshop.'],keyReturned:['عادت الأمانة. أصبح بإمكاننا تشغيل ورشة الجسر.','The key is home. The bridge workshop can work again.'],beamFull:['القطعة أطول من المسافة المتبقية. جرّب طولًا آخر.','That beam is longer than the remaining gap. Try another size.'],built:['الجسر ثابت! اعبر نحو الواحة.','The bridge is ready! Cross to the oasis.'],held:['نور يثبّت المضخة. دورك توصيل الأنابيب.','Noor is holding the pump. Your turn: connect the pipes.'],water:['وصل الماء! شاهد الواحة وهي تستعيد حياتها.','Water is flowing! Watch the oasis come to life.'],safe:['عدت إلى نقطة آمنة. إنجازاتك باقية.','Back at a safe checkpoint. Your work is still here.'],needKey:['نحتاج المفتاح أولًا. اتبع علامة الوجهة.','We need the key first. Follow the destination marker.'],needBridge:['أكمل الجسر أولًا، ثم نعيد الماء.','Finish the bridge first, then restore the water.'],
 restText:['العالم ينتظرك. التوقف لا يلغي إنجازك، والوقت يتوقف في المضمار أيضًا.','The world can wait. Pausing keeps your progress and pauses the circuit timer too.'],policy:['النقاط لقياس مهارة اللعب، لا الإيمان. لا أسلحة، ولا دردشة، ولا إعلانات، ولا صناديق حظ. العبارات الدينية ليست قدرات أو شرطًا للفوز.','Scores measure play, not faith. No weapons, chat, ads or loot boxes. Religious phrases are never power-ups or a condition for winning.'],
 bridgeHelp:['اختر قطعًا بطول ٢ أو ٣ أو ٤ أمتار لتغطية ٨ أمتار تمامًا. يمكن الحل بأكثر من طريقة. القطع تظهر في العالم، ويمكن التراجع قبل اكتمال الجسر.','Use 2-, 3- or 4-metre beams to span exactly 8 metres. More than one solution works. Beams appear in the world; undo is available until the bridge is complete.'],waterHelp:['اطلب من نور تثبيت المضخة عند العلامة البيضاء. اقترب من عجلات الصمامات ودوّرها. الأنبوب المتصل يتحول إلى فيروزي؛ تتبّع الماء حتى البركة.','Ask Noor to hold the pump at the white marker. Approach each valve and rotate it. Connected pipes turn turquoise. Follow the water to the pond.'],discovery:['أثر استكشاف','DISCOVERY'],found:['اكتشاف جديد في دفترك','A new discovery in your journal'],
 journalText:['هذا سجل لما فعلته في العالم، وليس اختبارًا لإيمانك أو ترتيبًا لأخلاقك.','This records what you changed in the world, not a test of faith or a ranking of character.'],j0:['أعدت الأمانة','YOU RETURNED WHAT WAS LOST'],j1:['بنيت جسرًا قابلًا للعبور','YOU BUILT A WALKABLE BRIDGE'],j2:['وصل الماء بالتعاون','WATER RESTORED TOGETHER'],j0d:['إعادة المفتاح مكّنت سالم من مساعدتك.','Returning the key enabled Salim to help.'],j1d:['جمعت أطوال القطع، وجربت بناءً يناسب الفجوة.','You combined beam lengths and tested a bridge that fits.'],j2d:['نور ثبّت المضخة وأنت أكملت المسار؛ لكل دور أهميته.','Noor held the pump while you connected the pipes. Both roles mattered.'],
 raceText:['اختر بيئة أصلية للمضمار. حرّك المركبة يمينًا ويسارًا، واقفز فوق الحواجز، واستخدم الاندفاع. تمرّ نقاط التحقق بالترتيب. لا سباق ضد الغرباء: تظهر محاولتك السابقة شبه شفافة بعد تسجيل جولة.','Choose an original circuit environment. Steer, hop over barriers, and boost. Pass checkpoints in order. No strangers to race: a translucent replay appears after you record a lap.'],raceKeys:['← → توجيه · Space قفز · Shift اندفاع · ↓ إبطاء · Esc إيقاف. المركبة تتقدم تلقائيًا.','← → STEER · SPACE HOP · SHIFT BOOST · ↓ BRAKE · ESC PAUSE. Forward movement is automatic.'],assistance:['المساعدة تحدّ من الابتعاد عن منتصف الطريق. تُفصل الأزمنة بحسب المسار والبيئة ونمط المساعدة.','Assist gently limits drifting from the centre. Records are separated by route, environment and assist setting.'],lap:['نقاط التحقق','CHECKPOINTS'],time:['وقت الجولة','LAP TIME'],best:['أفضل وقتك','YOUR BEST'],ghost:['محاولتك السابقة','YOUR RECORDED RUN'],none:['لم تسجل جولة بعد','NO LAP RECORDED YET'],personal:['المنافس الوحيد هنا هو محاولتك السابقة. ليس هذا لعبًا جماعيًا مباشرًا.','Your only opponent is your recorded run. This is not live multiplayer.'],bump:['لامست حاجزًا. عدّل المسار وواصل.','Barrier touched. Adjust your line and keep going.'],
 labTitle:['المرفقات: فحص قبل الدمج','ASSETS: INSPECT BEFORE INTEGRATION'],labText:['الأرشيف يحتوي نماذج سباق مضغوطة بـ Draco، وصوتًا وبيانات مسار. المصدر المذكور لعبة أخرى، ولا توجد رخصة استخدام تجاري موثقة ضمنه. هذه الأدوات محلية ولا ترفع الملفات إلى خادم.','The archive contains Draco-compressed racing models, sound, and route data. Its manifest names another game as the source, but supplies no documented commercial license. These tools are local and do not upload files.'],routeLabel:['تجربة بيانات المسار: اختر ملف track_data…json','TRY ROUTE DATA: SELECT track_data…json'],modelLabel:['فحص نموذج GLB: معلومات فقط، وليس عرضًا للنموذج','INSPECT GLB: METADATA ONLY, NOT A MODEL RENDER'],labPolicy:['لا تُنشر المرفقات على المستودع العام. المسار المستورد تجربة محلية معلّقة لحين توثيق الحقوق. لم تُدمج نماذج السيارة أو البيئات أو موسيقى المرفق في الإصدار العام.','Attachments are not published to the public repository. Imported routes are local evaluation only until rights are documented. The supplied car, environment meshes and music are not included in the public build.'],routeReady:['المسار جاهز محليًا. حوّلنا نقاطه إلى سطح قيادة أصلي للتجربة فقط.','Route ready locally. Its points have been converted into a simple original road surface for evaluation only.'],tryRoute:['جرّب المسار المحلي','TRY LOCAL ROUTE'],badRoute:['تعذر قراءة المسار. اختر مصفوفة صحيحة من نقاط ثلاثية الأبعاد.','Could not read the route. Select a valid array of 3D points.'],badModel:['ملف GLB غير صالح أو أكبر من الحد المسموح.','Invalid GLB file or file exceeds the size limit.'],localTag:['مسار محلي · حقوق غير موثقة','LOCAL ROUTE · RIGHTS UNVERIFIED'],originalTag:['مسار أصلي · نابغة','ORIGINAL NABIGHA ROUTE'],saved:['نسخة التقدم جاهزة','PROGRESS EXPORTED'],restored:['استعدنا تقدم البعثة','EXPEDITION PROGRESS RESTORED'],invalid:['ملف غير صالح. لم يتغير تقدمك.','Invalid file. Your progress was not changed.'],localSave:['الحفظ على هذا المتصفح. لا تُرسل بيانات اللعب إلى خادم. الخط الخارجي يحتاج اتصالًا أو تثبيتًا محليًا.','Progress stays in this browser. Gameplay data is not sent to a server. The external font requires a connection or local installation.'],saveFail:['الحفظ الدائم غير متاح. صدّر تقدمك من قائمة الإيقاف قبل الإغلاق.','Persistent saving is unavailable. Export progress from Pause before closing.'],resetRace:['هذه الجولة محفوظة. خذ استراحة أو جرّب تحسين مسارك.','Your lap is saved. Take a break or try a better line.'],biomeD0:['ضوء صباح ومياه فيروزية','Morning light and turquoise water'],biomeD1:['نجوم ومنصات مستقبلية','Stars and futuristic platforms'],biomeD2:['قباب زجاجية ومرجان','Glass domes and coral'],
 };
 function fresh(){return{version:1,stage:0,bridge:[],rot:[0,2,0,2],noor:false,discoveries:[],assist:true,biome:0,bests:{}}}
 function validate(s){
  if(!s||s.version!==1||!Number.isInteger(s.stage)||s.stage<0||s.stage>4||!Array.isArray(s.bridge)||s.bridge.length>4||!s.bridge.every(x=>[2,3,4].includes(x))||s.bridge.reduce((a,b)=>a+b,0)>8||!Array.isArray(s.rot)||s.rot.length!==4||!s.rot.every(x=>Number.isInteger(x)&&x>=0&&x<4)||typeof s.noor!=='boolean'||!Array.isArray(s.discoveries)||s.discoveries.length>6||!s.discoveries.every(x=>Number.isInteger(x)&&x>=0&&x<6)||typeof s.assist!=='boolean'||![0,1,2].includes(s.biome))throw Error('INVALID');
  const total=s.bridge.reduce((a,b)=>a+b,0);if(s.stage<2&&total!==0||s.stage===2&&total===8||s.stage>=3&&total!==8||s.noor&&s.stage<3||s.stage===4&&(!s.noor||s.rot.some((x,i)=>x!==[3,1,2,0][i])))throw Error('INCONSISTENT');
  const bests={};if(s.bests&&typeof s.bests==='object'&&!Array.isArray(s.bests))for(const [k,b]of Object.entries(s.bests).slice(-8)){
   if(!/^[a-zA-Z0-9_.-]{1,100}$/.test(k)||!b||!Number.isFinite(b.time)||b.time<=0||b.time>900||!Array.isArray(b.frames)||b.frames.length>4600||!b.frames.every(f=>Array.isArray(f)&&f.length===4&&f.every(Number.isFinite)&&f[0]>=0&&f[0]<=900&&f[1]>=0&&f[1]<=1500&&Math.abs(f[2])<=4.5&&f[3]>=0&&f[3]<=8)||b.frames.some((f,i)=>i&&f[0]<b.frames[i-1][0]))throw Error('INVALID_REPLAY');
   bests[k]={time:b.time,frames:b.frames.map(f=>[...f])};
  }
  return{...fresh(),stage:s.stage,bridge:[...s.bridge],rot:[...s.rot],noor:s.noor,discoveries:[...new Set(s.discoveries)],assist:s.assist,biome:s.biome,bests};
 }
 function normaliseRoute(raw){
  if(!Array.isArray(raw)||raw.length<12||raw.length>10000)throw Error('ROUTE_POINTS');
  let pts=raw.map(x=>Array.isArray(x?.[0])?x[0]:x);if(!pts.every(p=>Array.isArray(p)&&p.length===3&&p.every(n=>Number.isFinite(n)&&Math.abs(n)<1e7)))throw Error('ROUTE_VECTOR');
  const step=Math.max(1,Math.ceil(pts.length/512));pts=pts.filter((p,i)=>i%step===0);let minX=Infinity,minZ=Infinity,maxX=-Infinity,maxZ=-Infinity,minY=Infinity,maxY=-Infinity;
  for(const p of pts){minX=Math.min(minX,p[0]);maxX=Math.max(maxX,p[0]);minZ=Math.min(minZ,p[2]);maxZ=Math.max(maxZ,p[2]);minY=Math.min(minY,p[1]);maxY=Math.max(maxY,p[1]);}
  if(Math.max(maxX-minX,maxZ-minZ)<1e-5)throw Error('DEGENERATE');
  const scale=140/Math.max(maxX-minX,maxZ-minZ),cx=(minX+maxX)/2,cz=(minZ+maxZ)/2;
  pts=pts.map(p=>[(p[0]-cx)*scale,(p[1]-minY)*Math.min(scale,6/Math.max(1,maxY-minY)),(p[2]-cz)*scale]);
  // Flatten sharp banking/elevation from source; this is a sampled centreline, NOT the original environment mesh.
  pts=pts.filter((p,i)=>i===0||Math.hypot(p[0]-pts[i-1][0],p[2]-pts[i-1][2])>.035);
  if(pts.length<12)throw Error('DEGENERATE');return pts;
 }
 function routeInfo(pts){let lens=[0];for(let i=1;i<pts.length;i++)lens.push(lens[i-1]+Math.hypot(...v.sub(pts[i],pts[i-1])));const length=lens.at(-1);if(length<10||length>1500)throw Error('ROUTE_LENGTH');let hash=2166136261;for(const c of JSON.stringify(pts))hash=Math.imul(hash^c.charCodeAt(0),16777619)>>>0;return{pts,lens,length,id:'r'+hash.toString(16)};}
 function originalRoute(){const pts=[];for(let i=0;i<=260;i++){let a=i/260*TAU;pts.push([Math.sin(a)*(46+8*Math.sin(3*a)),1.2+1.2*Math.sin(a*2),Math.cos(a)*(39+5*Math.cos(2*a))]);}return routeInfo(pts);}
 function sample(r,d){d=clamp(d,0,r.length);let lo=0,hi=r.lens.length-1;while(lo<hi){const m=(lo+hi)>>1;if(r.lens[m]<d)lo=m+1;else hi=m;}let i=clamp(lo,1,r.pts.length-1),a=r.pts[i-1],b=r.pts[i],f=(d-r.lens[i-1])/Math.max(.0001,r.lens[i]-r.lens[i-1]);const p=a.map((x,k)=>mix(x,b[k],f));let dir=v.norm(v.sub(b,a)),right=v.norm([dir[2],0,-dir[0]]);return{p,dir,right,yaw:Math.atan2(-dir[0],-dir[2])};}
 function glbInfo(buffer){const d=new DataView(buffer);if(buffer.byteLength<20||d.getUint32(0,true)!==0x46546c67||d.getUint32(4,true)!==2||d.getUint32(8,true)!==buffer.byteLength)throw Error('GLB');const n=d.getUint32(12,true);if(n>buffer.byteLength-20||d.getUint32(16,true)!==0x4e4f534a)throw Error('GLB_JSON');const j=JSON.parse(new TextDecoder().decode(new Uint8Array(buffer,20,n)));return{meshes:j.meshes?.length||0,primitives:(j.meshes||[]).reduce((n,m)=>n+(m.primitives?.length||0),0),nodes:j.nodes?.length||0,skins:j.skins?.length||0,animations:j.animations?.length||0,extensions:j.extensionsRequired||j.extensionsUsed||[],draco:(j.meshes||[]).some(m=>m.primitives.some(p=>p.extensions?.KHR_draco_mesh_compression)),generator:j.asset?.generator||'unspecified'};}
 class Expedition{
  constructor(env){this.e=env;this.r=env.renderer;this.meshes={};this.world=[];this.colliders=[];this.active=false;this.type='world';this.panel='';this.keys=new Set();this.joy={x:0,y:0};this.camYaw=0;this.camPitch=.48;this.eye=[0,6,14];this.target=[0,1,4];this.time=0;this.noteEnd=0;this.selectedBeam=2;this.builder=false;this.checkpoint=[0,0,10];this.p={x:0,y:0,z:10,vy:0,yaw:0,ground:true,step:0,speed:0,glide:false,slide:0,lean:0,boost:0,cooldown:0,bump:0};this.ok=true;this.loaded=false;this.state=fresh();try{const t=localStorage.getItem(STORE);if(t)this.state=validate(JSON.parse(t));}catch(e){this.ok=false;}this.bloom=this.state.stage===4?1:0;this.route=originalRoute();this.localRoute=null;this.race=null;this.tick=0;this.discoveries=[[-13,0,7],[-8,0,-11],[10,0,11],[4,0,-12],[39,0,-7],[33,0,8]];this.pipeNodes=[[26,0],[29,0],[29,-3],[32,-3],[32,0]];this.lastUI='';this.setupUI();this.bind();}
  t(k){return WORDS[k]?.[this.e.settings().lang==='ar'?0:1]||k;}
  tr(a,b){return this.e.settings().lang==='ar'?a:b;}
  mk(b){return b.mesh(this.r);}
