  add(mesh,p=[0,0,0],s=[1,1,1],rot=[0,0,0],o={}){return{mesh,matrix:M.compose(p,s,rot),...o};}
  save(){try{localStorage.setItem(STORE,JSON.stringify(this.state));this.ok=true;}catch(e){this.ok=false;}return this.ok;}
  setupUI(){const root=document.createElement('section');root.id='globalScreen';root.className='global-screen';root.hidden=true;root.setAttribute('aria-label','Nabigha expedition');root.innerHTML=`<div class="gx-top"><div class="gx-brand"><span class="gx-emblem">✦</span><div><b id="gxTitle"></b><small id="gxSubtitle"></small></div></div><div class="gx-nav"><button class="gx-icon language" id="gxLang"></button><button class="gx-icon" id="gxBook" aria-label="Explorer journal">▤</button><button class="gx-icon" id="gxHelp" aria-label="Help">?</button><button class="gx-icon" id="gxPause" aria-label="Pause">Ⅱ</button></div></div><div class="gx-mission" id="gxMission"><b id="gxValue"></b><span id="gxObjective"></span></div><div class="gx-compass" id="gxCompass"><span class="arrow">➤</span><span></span></div><div class="gx-target" id="gxTarget" hidden></div><div class="gx-note" id="gxNote" role="status" aria-live="polite"></div><canvas class="gx-mini" id="gxMap" width="292" height="252" aria-label="Local map"></canvas><div class="gx-actions"><div id="gxBuilder" class="gx-builder" hidden><span class="gx-measure" id="gxLength"></span><button data-beam-gx="2">2 m</button><button data-beam-gx="3">3 m</button><button data-beam-gx="4">4 m</button><button id="gxUndo">↶</button></div><button id="gxInteract" hidden></button></div><div class="gx-touch"><div class="gx-joy" id="gxJoy"><i></i></div><div class="gx-driving" id="gxSteer" hidden><button id="gxLeft" aria-label="Steer left">←</button><button id="gxRight" aria-label="Steer right">→</button></div><div class="gx-buttons"><button id="gxAlt">ϟ<small></small></button><button id="gxJump">↑<small></small></button></div></div><div class="gx-race-meter" id="gxSpeed" hidden><strong>0</strong><small></small><div class="gx-race-bar"><i></i></div></div><div class="gx-desktop" id="gxKeys"></div>`;document.body.appendChild(root);this.ui=root;
   const overlay=document.createElement('div');overlay.className='gx-overlay';overlay.id='gxOverlay';overlay.hidden=true;overlay.innerHTML='<section id="gxDialog" class="gx-dialog" role="dialog" aria-modal="true" aria-labelledby="gxDialogTitle" tabindex="-1"></section>';document.body.appendChild(overlay);this.overlay=overlay;this.box=overlay.firstElementChild;
   this.$=id=>document.getElementById(id);
   this.importInput=document.createElement('input');this.importInput.type='file';this.importInput.accept='.json,application/json';this.importInput.hidden=true;document.body.appendChild(this.importInput);this.importInput.onchange=async()=>{const f=this.importInput.files[0];this.importInput.value='';if(f)await this.importSave(f);};
  }
  btn(k,a,cls=''){return`<button data-gx="${a}" class="${cls}">${this.t(k)}</button>`;}
  show(kind){this.focusBefore=document.activeElement;this.panel=kind;this.builder=false;this.clearInput();this.e.stopVoice();this.e.audio.stop();this.ui.dataset.panelOpen='true';this.overlay.hidden=false;this.drawPanel();this.box.focus();}
  drawPanel(){const T=k=>this.t(k),btn=(k,a,c)=>this.btn(k,a,c);let body='',title='',eyebrow='NABIGHA / GLOBAL 3.0 · PREVIEW';
   if(this.panel==='intro'){title=T('startTitle');body=`<p>${T('startText')}</p><div class="gx-policy">${T('startControls')}</div><div class="gx-dialog-actions">${btn('launch','resume','primary-gx')}${btn('guide','guide','subtle-gx')}</div>`;}
   if(this.panel==='pause'){title=T('pause');body=`<p>${T('restText')}</p><div class="gx-dialog-actions">${btn('resume','resume','primary-gx')}${btn('journal','journal')}${btn('guide','guide')}${btn('settings','settings')}${btn('race','race-select')}${btn('export','export')}${btn('import','import')}${btn('home','home','subtle-gx')}</div><div class="gx-policy">${T('policy')}</div>`;}
   if(this.panel==='guide'){title=T('guide');body=`<p>${this.type==='race'?T('raceText'):T('startText')}</p><div class="gx-policy">${this.type==='race'?T('raceKeys'):T('startControls')}</div>${this.type==='world'?`<h3>${T('bridge')}</h3><p>${T('bridgeHelp')}</p><h3>${T('pipe')}</h3><p>${T('waterHelp')}</p>`:''}<div class="gx-dialog-actions">${btn('resume','resume','primary-gx')}${btn('home','home','subtle-gx')}</div>`;}
   if(this.panel==='journal'){title=T('journal');const marks=[this.state.stage>=2,this.state.stage>=3,this.state.stage===4];body=`<p>${T('journalText')}</p>${marks.map((done,i)=>`<div class="gx-journal-row"><span>${done?'✓':'◇'}</span><div><b>${T('j'+i)}</b><p>${T('j'+i+'d')}</p></div></div>`).join('')}<div class="gx-stats"><div><strong>${this.state.discoveries.length} / 6</strong><small>${T('discovery')}</small></div><div><strong>${marks.filter(Boolean).length} / 3</strong><small>${this.tr('مهمات العالم','WORLD QUESTS')}</small></div></div><div class="gx-dialog-actions">${btn('resume','resume','primary-gx')}${btn('race','race-select')}${btn('export','export')}</div>`;}
   if(this.panel==='race-select'){title=T('race');body=`<p>${T('raceText')}</p><div class="gx-grid">${[0,1,2].map((x)=>`<button data-gx="biome-${x}" class="gx-biome" aria-pressed="${this.state.biome===x}"><span>${['◒','✧','≈'][x]}</span>${T(['beach','moon','sea'][x])}<small>${T('biomeD'+x)}</small></button>`).join('')}</div><div class="gx-dialog-actions"><button data-gx="assist" aria-pressed="${this.state.assist}">${T('assist')} · ${this.state.assist?this.tr('مفعّلة','ON'):this.tr('متوقفة','OFF')}</button></div><p>${T('assistance')}</p><div class="gx-dialog-actions">${btn('raceMode','race-start','primary-gx')}${btn('free','race-free')}${this.localRoute?btn('tryRoute','race-local'):''}${btn('leave','world','subtle-gx')}${btn('home','home','subtle-gx')}</div><div class="gx-policy">${T('personal')}</div>`;}
   if(this.panel==='race-result'){title=T('end');const q=this.race,b=this.state.bests[this.raceKey()];body=`<div class="gx-stats"><div><strong dir="ltr">${q?.timed?q.elapsed.toFixed(2)+' s':'—'}</strong><small>${T('time')}</small></div><div><strong>${q?.collected||0} / ${q?.coins.length||0}</strong><small>${this.tr('شرارات مهارة','SKILL SPARKS')}</small></div><div><strong dir="ltr">${b?b.time.toFixed(2)+' s':'—'}</strong><small>${T('best')}</small></div></div><p>${T('resetRace')}</p><div class="gx-dialog-actions">${btn('again','replay','primary-gx')}${btn('race','race-select')}${btn('leave','world')}${btn('home','home','subtle-gx')}</div><div class="gx-policy">${T('personal')}</div>`;}
   if(this.panel==='lab'){title=T('labTitle');body=`<p>${T('labText')}</p><div class="gx-stats"><div><strong>13</strong><small>GLB · Draco</small></div><div><strong>14</strong><small>${this.tr('ملفًا صوتيًا','AUDIO FILES')}</small></div><div><strong>3000</strong><small>${this.tr('نقطة في المسار','ROUTE POINTS')}</small></div></div><label class="gx-load-label">${T('routeLabel')}<input id="gxRouteFile" type="file" accept=".json,application/json"></label><div class="gx-local-report" id="gxRouteReport">${this.localRoute?T('routeReady'):this.tr('الصيغة الفعلية: [[position3, vector3], …]، وليست قاموس x/z كما يذكر الوصف.','Actual schema: [[position3, vector3], …], not the x/z dictionary described in the manifest.')}</div><canvas id="gxRouteMap" class="gx-diagram" width="600" height="240"></canvas><label class="gx-load-label">${T('modelLabel')}<input id="gxGLBFile" type="file" accept=".glb,model/gltf-binary"></label><div class="gx-local-report" id="gxGLBReport">${this.tr('لن يتم تنفيذ محتوى الملف. النماذج المضغوطة تحتاج قارئ glTF وفاكّ Draco قبل عرضها.','File contents are not executed. Compressed models need a glTF loader and Draco decoder before rendering.')}</div><div class="gx-policy gx-warning">${T('labPolicy')}</div><div class="gx-dialog-actions">${this.localRoute?btn('tryRoute','race-local','primary-gx'):''}${btn('home','home','subtle-gx')}</div>`;}
   this.box.innerHTML=`<span class="gx-eyebrow">${eyebrow}</span><h2 id="gxDialogTitle">${title}</h2>${body}<div class="gx-storage">${T(this.ok?'localSave':'saveFail')}</div>`;
   if(this.panel==='lab'){this.$('gxRouteFile').onchange=async e=>{const f=e.target.files[0];if(f)await this.importRoute(f);};this.$('gxGLBFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>30e6)throw Error('SIZE');const z=glbInfo(await f.arrayBuffer());this.$('gxGLBReport').textContent=`${f.name}\n${this.tr('مجسمات','Meshes')}: ${z.meshes} · ${this.tr('أجزاء','Primitives')}: ${z.primitives}\n${this.tr('حركات','Animations')}: ${z.animations} · ${this.tr('هياكل','Skins')}: ${z.skins}\nDraco: ${z.draco?'YES':'NO'}\n${z.extensions.join(', ')}\n${this.tr('فحص معلومات فقط. لم يُعرض النموذج ولم يُضمّن في اللعبة.','Metadata inspection only. The model was not rendered or embedded in the game.')}`;}catch(err){this.$('gxGLBReport').textContent=T('badModel');}};this.drawRouteMap(this.$('gxRouteMap'),this.localRoute||this.route);}
  }
  resume(){this.overlay.hidden=true;this.panel='';this.ui.dataset.panelOpen='false';this.clearInput();if(this.active){this.e.audio.unlock().then(ok=>{if(ok&&this.active&&!this.panel)this.e.audio.start();});this.e.canvas.focus();}else this.e.leave();}
  note(key,seconds=3.7){this.noteKey=key;this.noteEnd=this.time+seconds;this.$('gxNote').textContent=this.t(key);}
  clearInput(){this.keys.clear();this.joy={x:0,y:0};this.drag=null;this.steer=0;const k=this.$('gxJoy')?.firstElementChild;if(k)k.style.transform='';}
  bind(){
   this.$('gxLang').onclick=()=>{this.e.language();this.lastUI='';if(this.panel)this.drawPanel();};this.$('gxBook').onclick=()=>this.show('journal');this.$('gxHelp').onclick=()=>this.show('guide');this.$('gxPause').onclick=()=>this.show('pause');this.$('gxInteract').onclick=()=>this.interact();this.$('gxUndo').onclick=()=>this.undo();this.ui.querySelectorAll('[data-beam-gx]').forEach(b=>b.onclick=()=>{this.selectedBeam=+b.dataset.beamGx;this.sync();});
   const hold=(id,down,up)=>{const b=this.$(id);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);down();});b.addEventListener('pointerup',e=>{e.preventDefault();up?.();});b.addEventListener('pointercancel',()=>up?.());};
   hold('gxJump',()=>this.jump());hold('gxAlt',()=>this.type==='race'?this.boost():this.jump());hold('gxLeft',()=>this.steer=-1,()=>this.steer=0);hold('gxRight',()=>this.steer=1,()=>this.steer=0);
   const stick=this.$('gxJoy');stick.onpointerdown=e=>{if(!this.canPlay())return;e.preventDefault();this.joyID=e.pointerId;stick.setPointerCapture(e.pointerId);this.moveStick(e);};stick.onpointermove=e=>{if(e.pointerId===this.joyID)this.moveStick(e);};stick.onpointerup=stick.onpointercancel=()=>{this.joyID=null;this.joy={x:0,y:0};stick.firstElementChild.style.transform='';};
   this.box.addEventListener('click',e=>{const a=e.target.closest('[data-gx]')?.dataset.gx;if(!a)return;if(a.startsWith('biome-')){this.state.biome=+a.at(-1);this.save();this.drawPanel();return;}
    const act={resume:()=>this.resume(),pause:()=>this.show('pause'),guide:()=>this.show('guide'),journal:()=>this.show('journal'),home:()=>this.exit(),world:()=>this.e.start('world'),settings:()=>{this.resume();this.e.sharedSettings();},'race-select':()=>this.show('race-select'),'race-start':()=>this.e.start('race',{timed:true}),'race-free':()=>this.e.start('race',{timed:false}),'race-local':()=>this.e.start('race',{timed:true,local:true}),replay:()=>this.e.start('race',{timed:this.race?.timed,local:this.race?.local}),assist:()=>{this.state.assist=!this.state.assist;this.save();this.drawPanel();},export:()=>this.exportSave(),import:()=>this.importInput.click()};act[a]?.();
   });
   addEventListener('keydown',e=>{if(!this.active&&!this.panel)return;if(this.panel){if(e.code==='Escape'){e.preventDefault();this.resume();}if(e.code==='Tab'){const els=[...this.box.querySelectorAll('button:not([disabled]),input,select')].filter(x=>x.offsetParent);if(!els.length)return;const first=els[0],last=els.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===this.box)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}if(this.e.paused())return;if(['Space','Enter'].includes(e.code)&&e.target?.closest?.('button,input,select,textarea'))return;
    if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();this.keys.add(e.code);if(e.repeat)return;const handlers={Escape:()=>this.show('pause'),KeyP:()=>this.show('pause'),KeyH:()=>this.show('guide'),KeyM:()=>this.show('journal'),KeyE:()=>this.interact(),Enter:()=>this.interact(),Space:()=>this.jump(),KeyG:()=>this.jump(),ShiftLeft:()=>this.type==='race'&&this.boost(),Digit1:()=>this.selectedBeam=2,Digit2:()=>this.selectedBeam=3,Digit3:()=>this.selectedBeam=4,KeyZ:()=>this.undo()};handlers[e.code]?.();
   });addEventListener('keyup',e=>this.keys.delete(e.code));
   const c=this.e.canvas;c.addEventListener('pointerdown',e=>{if(this.canPlay()&&this.type==='world'){this.drag={id:e.pointerId,x:e.clientX,y:e.clientY};c.setPointerCapture(e.pointerId);} });c.addEventListener('pointermove',e=>{if(this.drag?.id===e.pointerId&&this.canPlay()){this.camYaw-=(e.clientX-this.drag.x)*.005;this.camPitch=clamp(this.camPitch+(e.clientY-this.drag.y)*.003,.24,.8);this.drag.x=e.clientX;this.drag.y=e.clientY;}});c.addEventListener('pointerup',()=>this.drag=null);c.addEventListener('pointercancel',()=>this.drag=null);
   addEventListener('blur',()=>{this.clearInput();if(this.active&&!this.panel)this.show('pause');});document.addEventListener('visibilitychange',()=>{if(document.hidden&&this.active){this.clearInput();if(!this.panel)this.show('pause');}});
  }
  moveStick(e){const r=this.$('gxJoy').getBoundingClientRect(),x=e.clientX-r.x-r.width/2,y=e.clientY-r.y-r.height/2,m=r.width*.33,n=Math.hypot(x,y),k=n>m?m/n:1;this.joy={x:x*k/m,y:y*k/m};this.$('gxJoy').firstElementChild.style.transform=`translate(${x*k}px,${y*k}px)`;}
  canPlay(){return this.active&&!this.panel&&!this.e.paused();}
  initMeshes(){if(this.loaded)return;this.loaded=true;let b;const mk=(name,b)=>this.meshes[name]=this.mk(b);
   b=new Builder();b.add('sphere',[0,.3,0],[.91,.31,1.65],'#fcf9de');b.add('sphere',[0,.64,-.45],[.65,.27,.73],'#16394f');b.add('sphere',[0,.88,.3],[.71,.37,.66],'#19c7c5');b.add('box',[0,.76,.55],[.65,.06,.7],'#76fbea',[.22,0,0],.15);for(const x of[-1,1]){b.add('sphere',[x*.77,.20,0],[.18,.25,1.22],'#124b6b');b.line([x*.87,.32,-1.0],[x*.87,.32,.95],.055,'#70ffda',.8);b.add('sphere',[x*.48,.32,-1.35],[.14,.08,.08],'#ffdf72',[0,0,0],.8);b.add('ring',[x*.78,.12,.87],[.21,1.2,.21],'#5ee8d9',[0,0,0],.5);}mk('vehicle',b);
   b=new Builder();b.add('box',[0,.65,0],[1.45,1.3,.9],'#ffb76a');b.add('box',[0,1.3,0],[1.5,.12,.98],'#fff0a5');for(let x of[-.45,0,.45])b.add('box',[x,.67,-.46],[.14,.8,.035],'#164459',[0,0,-.4]);mk('barrier',b);
   b=new Builder();b.add('box',[0,.07,0],[2.6,.14,2.4],'#25ccb9');for(let j=0;j<3;j++)b.tri([-.7,.16,.65-j*.5],[0,.16,.15-j*.5],[.7,.16,.65-j*.5],'#fff3a0',.7);mk('boostpad',b);
   b=new Builder();b.add('ring',[0,2,0],[3.75,2.3,3.75],'#71f9da',[Math.PI/2,0,0],.35);for(let x of[-3.6,3.6]){b.add('cylinder',[x,1,0],[.13,2,.13],'#f7f5d6');}mk('hoop',b);
   b=new Builder();b.add('box',[0,0,0],[.18,.9,.14],'#ffcf57');b.add('ring',[0,.57,0],[.26,1.7,.26],'#ffe885',[Math.PI/2,0,0],.3);b.add('box',[.18,-.32,0],[.4,.15,.15],'#ffd862');mk('key',b);
   b=new Builder();b.add('sphere',[0,0,0],[.18,.24,.18],'#ffe49a',[0,0,0],.65);mk('spark',b);
   b=new Builder();b.add('ring',[0,.1,0],[.92,1.3,.92],'#ffdf65',[0,0,0],.5);mk('beacon',b);
   b=new Builder();b.add('sphere',[0,0,0],[4.4,1,2.5],'#eefcff',[0,0,0],.4);mk('cloud',b);
   const plant=new Builder();plant.add('cylinder',[0,.7,0],[.13,1.4,.13],'#ae7955');for(let i=0;i<6;i++){let a=i*TAU/6;plant.line([0,1.6,0],[Math.cos(a)*1.2,1.9,Math.sin(a)*1.2],.16,'#60c39a');plant.add('sphere',[Math.cos(a)*.92,1.8,Math.sin(a)*.92],[.6,.13,.35],'#82e4ad',[0,-a,0]);}mk('palm',plant);
   this.guideAvatar=RayyanModel.model(this.r,'#e6ac48');this.buildWorld();
  }
  arch(b,x,y,z,w,h,col,rot=0){const pts=[];for(let j=0;j<=16;j++){const a=Math.PI*j/16;pts.push([x+Math.cos(a)*w/2,y+h-w/2+Math.sin(a)*w/2,z]);}for(let j=0;j<16;j++)b.line(pts[j],pts[j+1],.19,col);for(let s of[-1,1])b.line([x+s*w/2,y,z],[x+s*w/2,y+h-w/2,z],.19,col);}
  buildWorld(){let b=new Builder();const island=(x,z,r,c)=>{b.add('cylinder',[x,-.6,z],[r,1.2,r],c);b.add('cylinder',[x,.008,z],[r,.04,r],'#b3e0d3');b.add('cone',[x,-3.3,z],[r*.88,4.6,r*.88],'#546ba2',[Math.PI,0,0]);b.add('ring',[x,.06,z],[r-.55,1.3,r-.55],'#8ff6dd',[0,0,0],.12);};island(0,0,18,'#4a6b9b');island(35,0,12,'#5177a0');
   // Open courtyard and original regionally-inspired science workshop; no sacred text on props.
   b.add('cylinder',[0,.04,10],[2.8,.08,2.8],'#effadd');b.add('ring',[0,.12,10],[2.42,1,2.42],'#36d6c8',[0,0,0],.3);
