const test=require('node:test'),assert=require('node:assert/strict');const C=require('./core.js');
const steps=(s,k,n=60,boxes=[],cars=[])=>{let out=[];for(let i=0;i<n;i++)out.push(...C.tick(s,k,1/60,boxes,cars));return out;};
test('right is camera-right at eight headings; left is its inverse',()=>{for(let i=0;i<8;i++){let yaw=i*Math.PI/4,a=C.fresh();Object.assign(a,{x:0,z:80,yaw,speed:8});let b={...a,checkpointSafe:{...a.checkpointSafe},frames:[]};steps(a,{gas:1,steer:1},20);steps(b,{gas:1,steer:-1},20);let r=C.right(yaw);assert((a.x-0)*r[0]+(a.z-80)*r[1]>0);assert((b.x-0)*r[0]+(b.z-80)*r[1]<0);}});
test('gas starts stationary car and brake stops before reversing',()=>{let s=C.fresh();assert.equal(s.speed,0);steps(s,{gas:1},120);assert(s.speed>15);steps(s,{brake:1},150);assert(s.speed<0&&s.speed>=-5);});
test('neutral drag and handbrake reduce speed',()=>{let s=C.fresh();s.speed=12;steps(s,{handbrake:1},30);assert(s.speed<2);});
test('all 25 junctions and connecting street edges exist',()=>{for(let x of C.axes)for(let z of C.axes)assert(C.roadAt(x,z));for(let a of C.axes)for(let n=-185;n<185;n++)assert(C.roadAt(a,n)&&C.roadAt(n,a));assert(!C.roadAt(40,40));});
test('bridge supports independent ground underpass and upper carriageway',()=>{assert.equal(C.surface(0,0,0),0);assert.equal(C.surface(0,0,13),13);assert.equal(C.bridgeHeight(-176),0);assert.equal(C.bridgeHeight(176),0);});
test('driving up the west ramp reaches the raised bridge',()=>{let s=C.fresh(false);Object.assign(s,{x:-180,z:3,y:0,yaw:Math.PI/2});steps(s,{gas:1},360);assert(s.x>-108&&s.y>12.8);});
test('waterfront ramp creates real airborne motion and landing',()=>{let s=C.fresh(false);Object.assign(s,{x:86,z:160,y:0,yaw:Math.PI/2,speed:17});steps(s,{gas:1},200);assert(s.airSeconds>.2);assert(s.ground&&s.y<.2);});
test('northern road is a climb rather than a painted slope',()=>{assert(C.baseHeight(0,-160)>8);let s=C.fresh(false);Object.assign(s,{x:-4,z:-84,y:0,yaw:0});steps(s,{gas:1},400);assert(s.y>7);});
test('obstacles stop without damage states or violent events',()=>{let s=C.fresh();Object.assign(s,{x:0,z:15,speed:10});let events=steps(s,{gas:1},100,[{x:0,z:0,w:10,d:10,y:0,h:20}]);assert(s.z>6);assert(events.includes('care'));assert(!('health' in s));});
test('traffic moves and yields to a car ahead',()=>{let bots=C.makeTraffic(),p=C.fresh();C.trafficStep(bots,.1,p,0);let a={...bots[0]};C.trafficStep(bots,1,{x:200,z:200,y:0},0);assert(bots[0].u>a.u);let c=bots[0],f=C.forward(c.yaw);C.trafficStep(bots,.1,{x:c.x+f[0]*7,z:c.z+f[1]*7,y:c.y},0);assert(c.waiting);});
test('finish checkpoint on overpass cannot trigger from below',()=>{let s=C.fresh();Object.assign(s,{x:0,z:0,y:0,checkpoint:6});steps(s,{},1);assert.equal(s.checkpoint,6);s.y=13;steps(s,{},1);assert.equal(s.checkpoint,7);assert(s.finished);});
test('free driving remains playable after destinations',()=>{let s=C.fresh(false);Object.assign(s,{x:0,z:0,y:13,checkpoint:6});steps(s,{},1);assert.equal(s.checkpoint,7);assert(!s.finished);});
test('progress validator is bounded and rejects corrupt input',()=>{let save={version:1,bests:{'noor-city-v1-1':{time:25,frames:[[0,0,0,0,0],[25,20,0,-20,.3]]}},deliveries:[0],colour:2};let copy=C.validateSave(save);assert.equal(copy.colour,2);copy.bests['noor-city-v1-1'].frames[0][1]=6;assert.equal(save.bests['noor-city-v1-1'].frames[0][1],0);assert.throws(()=>C.validateSave({...save,deliveries:[9]}));assert.throws(()=>C.validateSave({...save,bests:{evil:{time:1,frames:[]}}}));});
test('recovery preserves achievements and timing',()=>{let s=C.fresh();s.checkpoint=2;s.elapsed=15;s.speed=20;s.x=190;C.recover(s);assert.equal(s.x,-156);assert.equal(s.checkpoint,2);assert.equal(s.elapsed,15);});
test('bounded steps do not teleport or produce non-finite values',()=>{let s=C.fresh();steps(s,{gas:1,steer:1},12000);for(let k of['x','y','z','speed','yaw'])assert(Number.isFinite(s[k]));assert(Math.abs(s.x)<=202&&Math.abs(s.z)<=202);});
test('complete non-circular city tour through physical steering and bridge access',()=>{let s=C.fresh();let way=[[-156,80],[-156,-80],[-156,-156],[0,-156],[156,-156],[156,-80],[156,160],[0,160],[-184,160],[-184,0],[0,0]],i=0;for(let j=0;j<45000&&!s.finished;j++){const p=way[i],dist=Math.hypot(p[0]-s.x,p[1]-s.z);if(dist<9&&i<way.length-1)i++;let target=way[i],wanted=Math.atan2(target[0]-s.x,-(target[1]-s.z)),err=Math.atan2(Math.sin(wanted-s.yaw),Math.cos(wanted-s.yaw));let steer=C.clamp(err*2.4,-1,1);C.tick(s,{steer,gas:Math.abs(err)<.8&&s.speed<12?1:0,brake:Math.abs(err)>.75&&s.speed>5?1:0},1/60);}
 assert.equal(s.checkpoint,7,JSON.stringify({i,x:s.x,z:s.z,y:s.y,cp:s.checkpoint}));assert(s.finished&&s.y>12);});
