/* City activity controller. Saves are separate from expedition/legacy racing saves. */
class CityDriver {
 constructor(g){this.g=g;this.r=g.r;this.world=null;this.state=null;this.traffic=[];this.inputs={gas:0,brake:0,steer:0,handbrake:0};this.store={version:1,bests:{},deliveries:[],colour:0};this.storageOK=true;this.noteUntil=0;this.noteText='';this.viewYaw=0;this.oldEye=null;
  try{const raw=localStorage.getItem('nabigha.city-drive.v1');if(raw)this.store=CityCore.validateSave(JSON.parse(raw));}catch(e){this.storageOK=false;}
  this.makeUI();
 }
 tr(a,b){return this.g.tr(a,b);}
 active(){return this.g.active&&this.g.type==='race'&&this.g.race?.city===true;}
 save(){try{localStorage.setItem('nabigha.city-drive.v1',JSON.stringify(this.store));this.storageOK=true;}catch(e){this.storageOK=false;}}
 key(){return 'noor-city-v1-'+Number(this.state?.assist??this.g.state.assist);}
 async start(opts={}){this.g.initMeshes();if(!this.world)this.world=new CityWorldArt(this.r);this.g.active=true;this.g.type='race';this.g.panel='';this.g.ui.hidden=false;this.g.overlay.hidden=true;this.g.builder=false;this.g.clearInput();this.clear();
  this.state=CityCore.fresh(opts.timed!==false,this.g.state.assist);this.state.city=true;this.state.colour=this.store.colour;this.g.race=this.state;this.traffic=CityCore.makeTraffic();CityCore.trafficStep(this.traffic,0,this.state,0);this.oldEye=null;this.g.e.palette('linear-gradient(#3886c0,#9adce2 65%,#e9e8d1)',[.63,.79,.78]);document.body.dataset.cityDriving='true';document.body.dataset.globalMode='race';this.hud.hidden=false;
  this.note(this.tr('اضغط ↑ للتسارع. يمين ويسار للتوجيه. اختر طريقك إلى العلامة.','Hold ↑ to accelerate. ← → steer. Choose your own route to the marker.'),7);
  await this.g.e.audio.unlock();if(this.active()&&!this.g.panel&&!clearStart.open)this.g.e.audio.start();this.g.e.canvas.focus();this.sync();
 }
 clear(){this.inputs={gas:0,brake:0,steer:0,handbrake:0};this.pulseBrake=0;}
 target(){const s=this.state;if(!s)return null;let goal=CityCore.goals[s.checkpoint];if(!goal)return null;
  if(goal.y===13&&s.y<4){const x=s.x<0?-184:184;return{x,z:0,y:0,name:[x<0?'مدخل الجسر الغربي':'مدخل الجسر الشرقي',x<0?'WEST RAMP ENTRANCE':'EAST RAMP ENTRANCE']};}return goal;
 }
 update(dt){if(!this.active()||!this.g.canPlay()||clearStart.open||clearStart.countdown>0)return;const q=this.state;if(q.finished)return;
  this.pulseBrake=Math.max(0,(this.pulseBrake||0)-dt);const k=this.g.keys,input={steer:(k.has('ArrowRight')||k.has('KeyD')?1:0)-(k.has('ArrowLeft')||k.has('KeyA')?1:0)+(this.g.steer||0)+this.inputs.steer,gas:(k.has('ArrowUp')||k.has('KeyW')?1:0)||this.inputs.gas,brake:(k.has('ArrowDown')||k.has('KeyS')?1:0)||this.inputs.brake,handbrake:k.has('Space')||this.pulseBrake>0};
  CityCore.trafficStep(this.traffic,dt,q,q.elapsed);const events=CityCore.tick(q,input,dt,this.world.boxes,this.traffic);
  this.g.time+=dt;this.g.tick++;this.g.e.audio.intensity=Math.abs(q.speed)/28;
  for(const e of events){if(e==='care')this.note(this.tr('تمهّل واترك مساحة للآخرين. اضغط ↓ للرجوع عند الحاجة.','Slow down and leave room. Hold ↓ to reverse when needed.'),3);if(e==='checkpoint'){this.g.e.audio.fx('good');this.note(this.tr('وصلت! وجهتك التالية تظهر على الخريطة.','Checkpoint reached! Your next destination is on the map.'),2.5);}if(e==='finish')this.finish();}
 }
 ghost(){let b=this.store.bests[this.key()],s=this.state;if(!b||!s.timed||s.finished||!b.frames.length)return null;let fs=b.frames,lo=0,hi=fs.length-1;while(lo<hi){let m=(lo+hi)>>1;if(fs[m][0]<s.elapsed)lo=m+1;else hi=m;}let a=fs[Math.max(0,lo-1)],d=fs[lo],f=CityCore.clamp((s.elapsed-a[0])/Math.max(.001,d[0]-a[0]),0,1),dy=Math.atan2(Math.sin(d[4]-a[4]),Math.cos(d[4]-a[4]));return{x:CityCore.lerp(a[1],d[1],f),y:CityCore.lerp(a[2],d[2],f),z:CityCore.lerp(a[3],d[3],f),yaw:a[4]+dy*f,wheel:s.wheel,steer:0};}
 camera(dt){const s=this.state,f=CityCore.forward(s.yaw),distance=innerWidth<600?10.3:9.5,eye=[s.x-f[0]*distance,s.y+4.3,s.z-f[1]*distance],target=[s.x+f[0]*5,s.y+1.1,s.z+f[1]*5];
  if(!this.lightSaved){this.lightSaved=this.r.lightVP;this.lightChanged=true;}this.r.lightVP=N3.M.mul(N3.M.ortho(-30,30,-30,30,1,145),N3.M.lookAt([s.x-28,s.y+60,s.z+25],[s.x,s.y,s.z]));
  if(!this.oldEye)this.oldEye=eye;const k=1-Math.exp(-dt*5.5);this.oldEye=this.oldEye.map((x,i)=>CityCore.lerp(x,eye[i],k));this.r.fov=innerWidth<600?67:60;return{eye:this.oldEye,target};
 }
 scene(){return this.world.scene(this.state,this.traffic,this.ghost(),this.target());}
 note(t,seconds=3){this.noteText=t;this.noteUntil=(this.state?.elapsed||0)+seconds;}
 delivery(){let s=this.state;return CityCore.deliveryStops.findIndex((g,i)=>!this.store.deliveries.includes(i)&&Math.hypot(s.x-g.x,s.z-g.z)<8&&Math.abs(s.y-CityCore.baseHeight(g.x,g.z))<2);}
 interact(){if(!this.g.canPlay())return;const i=this.delivery();if(i<0)return;if(Math.abs(this.state.speed)>1){this.note(this.tr('قف بأمان أولًا، ثم سلّم الأمانة.','Stop safely, then deliver the parcel.'));return;}this.store.deliveries.push(i);this.save();this.note(this.tr('وصلت الأمانة. شكرًا لقيادتك المتأنية.','Parcel delivered. Thank you for driving with care.'));this.g.e.audio.fx('good');}
 finish(){const s=this.state;const old=this.store.bests[this.key()];if(s.frames.length<8000)s.frames.push([s.elapsed,s.x,s.y,s.z,s.yaw]);if(s.timed&&s.elapsed>0&&s.elapsed<1280&&s.frames.length&&(!old||s.elapsed<old.time)){this.store.bests[this.key()]={time:s.elapsed,frames:s.frames.map(f=>[...f])};this.save();}this.g.show('race-result');}
 makeUI(){const h=document.createElement('section');h.id='cityHud';h.hidden=true;h.innerHTML=`<header class="city-top"><div><small>NOOR CITY / 01</small><b id="cityTitle"></b></div><nav><button id="cityLanguage">EN</button><button id="cityMapBtn" aria-label="Map">▦</button><button id="cityPause" aria-label="Pause">Ⅱ</button><button data-cs="choose" aria-label="Choose an activity">⌂</button></nav></header><div class="city-mission"><b id="cityObjective"></b><span id="cityDirection"></span></div><div class="city-note" id="cityNote"></div><div class="city-speed"><strong id="citySpeed">0</strong><small id="cityUnit"></small><span id="cityTime"></span></div><canvas id="cityMap" width="240" height="240"></canvas><div class="city-pedals"><button id="cityBrake">↓<small></small></button><button id="cityGas">↑<small></small></button></div><div class="city-steering"><button id="cityLeft" aria-label="Steer left">←</button><button id="cityRight" aria-label="Steer right">→</button></div><button id="cityDeliver" hidden></button><div id="cityKeys" class="city-keys"></div>`;document.body.appendChild(h);this.hud=h;
  const hold=(id,k,value)=>{const b=document.getElementById(id);b.addEventListener('pointerdown',e=>{if(!this.g.canPlay()||clearStart.open)return;e.preventDefault();b.setPointerCapture(e.pointerId);this.inputs[k]=value;b.classList.add('held');});for(const event of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>{if(this.inputs[k]===value)this.inputs[k]=0;b.classList.remove('held');});};
  hold('cityLeft','steer',-1);hold('cityRight','steer',1);hold('cityGas','gas',1);hold('cityBrake','brake',1);
  document.getElementById('cityPause').onclick=()=>this.g.show('pause');document.getElementById('cityMapBtn').onclick=()=>this.g.show('city-map');document.getElementById('cityLanguage').onclick=()=>{this.g.e.language();this.sync();};document.getElementById('cityDeliver').onclick=()=>this.interact();
  this.g.box.addEventListener('click',e=>{const a=e.target.closest('[data-city]')?.dataset.city;if(a==='recover'){CityCore.recover(this.state);this.g.resume();}if(a==='restart')this.g.e.start('race',{timed:this.state.timed});if(a==='export')this.exportSave();if(a==='import')this.fileInput.click();});
  this.fileInput=document.createElement('input');this.fileInput.type='file';this.fileInput.accept='.json,application/json';this.fileInput.hidden=true;document.body.appendChild(this.fileInput);this.fileInput.onchange=async()=>{const f=this.fileInput.files[0];this.fileInput.value='';if(!f)return;await this.importSave(f);};
 }
 sync(){const active=this.active();this.hud.hidden=!active;document.body.dataset.cityDriving=String(active);if(!active){if(this.lightChanged){this.r.lightVP=this.lightSaved;this.lightSaved=null;this.lightChanged=false;}return;}const q=this.state,goal=this.target(),$=id=>document.getElementById(id),lang=this.g.e.settings().lang;
  $('cityTitle').textContent=this.tr('مدينة النور · أفق GT','NOOR CITY · HORIZON GT');$('cityLanguage').textContent=lang==='ar'?'EN':'عربي';$('citySpeed').textContent=Math.round(Math.abs(q.speed)*3.6);$('cityUnit').textContent=this.tr('كم/س · سرعة افتراضية','km/h · game speed');$('cityTime').textContent=q.timed?q.elapsed.toFixed(1)+' s':this.tr('استكشاف حر','FREE DRIVE');
  $('cityObjective').textContent=goal?`${q.checkpoint+1} / ${CityCore.goals.length} · ${goal.name[lang==='ar'?0:1]}`:this.tr('اكتشفت الوجهات! استكشف الشوارع بحرية.','All destinations found! Explore the streets.');
  if(goal){const angle=Math.atan2(goal.x-q.x,-(goal.z-q.z))-q.yaw,d=Math.hypot(goal.x-q.x,goal.z-q.z);$('cityDirection').textContent=(Math.abs(angle)<.35?'↑':Math.sin(angle)>0?'↱':'↰')+' '+Math.round(d)+' m';}else $('cityDirection').textContent='✓';
  $('cityNote').textContent=q.elapsed<this.noteUntil?this.noteText:'';$('cityGas').querySelector('small').textContent=this.tr('تسارع','GAS');$('cityBrake').querySelector('small').textContent=this.tr('فرامل / رجوع','BRAKE / REVERSE');$('cityKeys').textContent=this.tr('↑ تسارع · ↓ فرامل ثم رجوع · ← → توجيه · Space فرامل يد · E تسليم · M خريطة','↑ GAS · ↓ BRAKE / REVERSE · ← → STEER · SPACE HANDBRAKE · E DELIVER · M MAP');
  for(const [id,ar,en]of[['cityLeft','انعطف يسارًا','Steer left'],['cityRight','انعطف يمينًا','Steer right'],['cityPause','إيقاف مؤقت','Pause'],['cityMapBtn','خريطة المدينة','City map']])$(id).setAttribute('aria-label',this.tr(ar,en));
  const delivery=this.delivery();$('cityDeliver').hidden=delivery<0||this.g.panel!=='';if(delivery>=0)$('cityDeliver').textContent=(Math.abs(q.speed)>1?this.tr('قف لتسلّم: ','Stop to deliver: '):this.tr('سلّم: ','Deliver: '))+CityCore.deliveryStops[delivery].name[lang==='ar'?0:1];
  document.body.classList.toggle('city-paused',!!this.g.panel||!!modalKind||clearStart.open);if(this.g.tick%8===0)this.map($('cityMap'));
 }
 map(canvas){if(!canvas||!this.state)return;const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,sc=(Math.min(w,h)-22)/410,to=(x,z)=>[w/2+x*sc,h/2+z*sc];c.clearRect(0,0,w,h);c.fillStyle='#102b42';c.fillRect(0,0,w,h);c.strokeStyle='#587a84';c.lineWidth=3;for(const a of CityCore.axes){c.beginPath();c.moveTo(...to(a,-190));c.lineTo(...to(a,190));c.moveTo(...to(-190,a));c.lineTo(...to(190,a));c.stroke();}c.strokeStyle='#edc776';c.lineWidth=3.5;c.beginPath();c.moveTo(...to(-176,0));c.lineTo(...to(176,0));c.stroke();
  const s=this.state,g=this.target();if(g){c.strokeStyle='#76e6c9';c.lineWidth=2;c.setLineDash([4,3]);c.beginPath();CityCore.shortestPath(s,g).forEach((p,i)=>i?c.lineTo(...to(...p)):c.moveTo(...to(...p)));c.stroke();c.setLineDash([]);c.fillStyle='#ffe078';c.beginPath();c.arc(...to(g.x,g.z),6,0,Math.PI*2);c.fill();}
  for(const d of CityCore.deliveryStops){c.fillStyle='#87cbf4';const p=to(d.x,d.z);c.fillRect(p[0]-2,p[1]-2,4,4);}c.save();c.translate(...to(s.x,s.z));c.rotate(s.yaw);c.beginPath();c.moveTo(0,-7);c.lineTo(5,5);c.lineTo(-5,5);c.closePath();c.fillStyle='#fff';c.fill();c.restore();c.font='bold 12px Arial';c.fillStyle='#e3ecde';c.fillText('N',w-18,17);
 }
 panel(){const b=(text,action)=>`<button data-city="${action}">${text}</button>`,title=this.g.panel==='race-result'?this.tr('جولة المدينة اكتملت','CITY TOUR COMPLETE'):this.g.panel==='city-map'?this.tr('اختر طريقك عبر المدينة','CHOOSE YOUR WAY THROUGH THE CITY'):this.tr('وقفة آمنة','A SAFE BREAK');
  this.g.box.innerHTML=`<span class="gx-eyebrow">NOOR CITY · REVIEW</span><h2 id="gxDialogTitle">${title}</h2>${this.g.panel==='city-map'?'<canvas id="cityLargeMap" width="600" height="540" style="width:100%;max-height:50vh;object-fit:contain"></canvas>':`<p>${this.tr('قد سيارة بأربع عجلات عبر الشوارع المتصلة. اصعد الجسر من طرفيه؛ يمكنك المرور تحته من الشوارع المتقاطعة. الأزرق على الخريطة يشير إلى أمانات اختيارية: قف ثم اضغط E لتسليمها.','Drive a four-wheel car through connected streets. Access the overpass from either end; cross underneath on the other streets. Blue markers are optional parcels: stop and press E to deliver.')}</p>`}<p>${this.tr('↑ تسارع · ↓ فرامل ثم رجوع · ← → توجيه. لا قفز بزر؛ ترتفع السيارة فقط على المنحدر.','↑ accelerate · ↓ brake then reverse · ← → steer. There is no jump button; ramps lift the car.')}</p><div class="gx-dialog-actions"><button data-gx="resume" class="primary-gx">${this.tr('تابع القيادة','RESUME')}</button>${b(this.tr('أعدني إلى نقطة آمنة','RECOVER SAFELY'),'recover')}${b(this.tr('جولة جديدة','NEW TOUR'),'restart')}${b(this.tr('حفظ تقدم المدينة','EXPORT CITY PROGRESS'),'export')}${b(this.tr('استعادة تقدم المدينة','IMPORT CITY PROGRESS'),'import')}<button data-cs="choose">${this.tr('اختر نشاطًا','CHOOSE AN ACTIVITY')}</button></div><p class="gx-storage">${this.tr(this.storageOK?'إنجازات المدينة محفوظة محليًا. الموضع الحالي لا يستمر بعد إغلاق اللعبة.':'الحفظ غير متاح؛ صدّر نسخة تقدم.',this.storageOK?'City achievements are saved locally. Current position does not persist after closing.':'Storage unavailable; export progress.')} ${this.tr('لا أضرار أو نقاط دينية.','No damage or religious scoring.')}</p>`;this.map(document.getElementById('cityLargeMap'));
 }
 exportSave(){this.g.download('nabigha-city-progress.json',JSON.stringify(this.store,null,2));}
 async importSave(file){try{if(!file||file.size>2e6)throw Error('SIZE');const s=CityCore.validateSave(JSON.parse(await file.text()));this.store=s;this.save();if(this.state)this.state.colour=s.colour;this.note(this.tr('استعدنا إنجازات المدينة.','City achievements restored.'));return true;}catch(e){this.note(this.tr('ملف غير صالح. لم يتغير تقدمك.','Invalid file. Your progress was not changed.'));return false;}}
 snapshot(){return{version:'3.0.2-city-review.1',active:this.active(),state:this.state?JSON.parse(JSON.stringify(this.state)):null,traffic:this.traffic.map(x=>({...x})),storageOK:this.storageOK,saved:JSON.parse(JSON.stringify(this.store)),stats:{roads:10,junctions:25,blocks:16,buildings:this.world?.buildings||0,roadSpan:380,bridgeHeight:13,traffic:10}};}
}
